[
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/7451",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/7451/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/7451/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/7451/events",
        "html_url": "https://github.com/kivy/kivy/pull/7451",
        "id": 842650393,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjAyMTc2MzAz",
        "number": 7451,
        "title": "Docs: Fix Type Error when creating bytes from array in Python 3",
        "user": {
            "login": "salt-die",
            "id": 53280662,
            "node_id": "MDQ6VXNlcjUzMjgwNjYy",
            "avatar_url": "https://avatars.githubusercontent.com/u/53280662?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/salt-die",
            "html_url": "https://github.com/salt-die",
            "followers_url": "https://api.github.com/users/salt-die/followers",
            "following_url": "https://api.github.com/users/salt-die/following{/other_user}",
            "gists_url": "https://api.github.com/users/salt-die/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/salt-die/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/salt-die/subscriptions",
            "organizations_url": "https://api.github.com/users/salt-die/orgs",
            "repos_url": "https://api.github.com/users/salt-die/repos",
            "events_url": "https://api.github.com/users/salt-die/events{/privacy}",
            "received_events_url": "https://api.github.com/users/salt-die/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 56554,
                "node_id": "MDU6TGFiZWw1NjU1NA==",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Component:%20documentation",
                "name": "Component: documentation",
                "color": "87edb5",
                "default": false,
                "description": "Documentation or examples"
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": {
            "url": "https://api.github.com/repos/kivy/kivy/milestones/32",
            "html_url": "https://github.com/kivy/kivy/milestone/32",
            "labels_url": "https://api.github.com/repos/kivy/kivy/milestones/32/labels",
            "id": 6197496,
            "node_id": "MDk6TWlsZXN0b25lNjE5NzQ5Ng==",
            "number": 32,
            "title": "2.1.0",
            "description": "",
            "creator": {
                "login": "matham",
                "id": 1644286,
                "node_id": "MDQ6VXNlcjE2NDQyODY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1644286?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/matham",
                "html_url": "https://github.com/matham",
                "followers_url": "https://api.github.com/users/matham/followers",
                "following_url": "https://api.github.com/users/matham/following{/other_user}",
                "gists_url": "https://api.github.com/users/matham/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/matham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matham/subscriptions",
                "organizations_url": "https://api.github.com/users/matham/orgs",
                "repos_url": "https://api.github.com/users/matham/repos",
                "events_url": "https://api.github.com/users/matham/events{/privacy}",
                "received_events_url": "https://api.github.com/users/matham/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 4,
            "closed_issues": 103,
            "state": "open",
            "created_at": "2020-12-09T21:13:35Z",
            "updated_at": "2021-05-28T19:39:34Z",
            "due_on": null,
            "closed_at": null
        },
        "comments": 0,
        "created_at": "2021-03-28T03:18:29Z",
        "updated_at": "2021-03-28T06:11:31Z",
        "closed_at": "2021-03-28T06:11:31Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/7451",
            "html_url": "https://github.com/kivy/kivy/pull/7451",
            "diff_url": "https://github.com/kivy/kivy/pull/7451.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/7451.patch"
        },
        "body": "The original line `buf = b''.join(map(chr, buf))` raises the following error in 3.8.6:\r\n    `TypeError: sequence item 0: expected a bytes-like object, str found`\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/7488",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/7488/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/7488/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/7488/events",
        "html_url": "https://github.com/kivy/kivy/pull/7488",
        "id": 863110551,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjE5NTczMTc5",
        "number": 7488,
        "title": "FocusBehavior: Fix assumption that modifiers is always a set.",
        "user": {
            "login": "matham",
            "id": 1644286,
            "node_id": "MDQ6VXNlcjE2NDQyODY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1644286?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/matham",
            "html_url": "https://github.com/matham",
            "followers_url": "https://api.github.com/users/matham/followers",
            "following_url": "https://api.github.com/users/matham/following{/other_user}",
            "gists_url": "https://api.github.com/users/matham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/matham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/matham/subscriptions",
            "organizations_url": "https://api.github.com/users/matham/orgs",
            "repos_url": "https://api.github.com/users/matham/repos",
            "events_url": "https://api.github.com/users/matham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/matham/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 56553,
                "node_id": "MDU6TGFiZWw1NjU1Mw==",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Component:%20Widgets",
                "name": "Component: Widgets",
                "color": "87edb5",
                "default": false,
                "description": "kivy/uix, style.kv"
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": {
            "url": "https://api.github.com/repos/kivy/kivy/milestones/32",
            "html_url": "https://github.com/kivy/kivy/milestone/32",
            "labels_url": "https://api.github.com/repos/kivy/kivy/milestones/32/labels",
            "id": 6197496,
            "node_id": "MDk6TWlsZXN0b25lNjE5NzQ5Ng==",
            "number": 32,
            "title": "2.1.0",
            "description": "",
            "creator": {
                "login": "matham",
                "id": 1644286,
                "node_id": "MDQ6VXNlcjE2NDQyODY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1644286?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/matham",
                "html_url": "https://github.com/matham",
                "followers_url": "https://api.github.com/users/matham/followers",
                "following_url": "https://api.github.com/users/matham/following{/other_user}",
                "gists_url": "https://api.github.com/users/matham/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/matham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/matham/subscriptions",
                "organizations_url": "https://api.github.com/users/matham/orgs",
                "repos_url": "https://api.github.com/users/matham/repos",
                "events_url": "https://api.github.com/users/matham/events{/privacy}",
                "received_events_url": "https://api.github.com/users/matham/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 4,
            "closed_issues": 103,
            "state": "open",
            "created_at": "2020-12-09T21:13:35Z",
            "updated_at": "2021-05-28T19:39:34Z",
            "due_on": null,
            "closed_at": null
        },
        "comments": 3,
        "created_at": "2021-04-20T18:30:50Z",
        "updated_at": "2021-04-21T17:42:04Z",
        "closed_at": "2021-04-21T17:42:03Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/7488",
            "html_url": "https://github.com/kivy/kivy/pull/7488",
            "diff_url": "https://github.com/kivy/kivy/pull/7488.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/7488.patch"
        },
        "body": "<!--\r\nThank you for pull request.\r\n\r\nBelow are items maintainers should consider when merging the PR. Feel free to suggest a `unit@` label or check-mark the others as appropriate.\r\n\r\n-->\r\nMaintainer merge checklist\r\n* [ ] Title is descriptive/clear for inclusion in release notes.\r\n* [ ] Applied a `Component: xxx` label.\r\n* [ ] Applied the `api-deprecation` or `api-break` label.\r\n* [ ] Applied the `release-highlight` label to be highlighted in release notes.\r\n* [ ] Added to the milestone version it was merged into.\r\n* [ ] **Unittests** are included in PR.\r\n* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.\r\n\r\n\r\nI got the following error on a linux computer. Not sure what exactly I did, but it happened periodically:\r\n\r\n```\r\nERROR  ] [Traceback (most recent call last)]\r\n  File \"/home/cpl/venv_ceed/lib/python3.8/site-packages/kivy/base.py\", line 347, in mainloop\r\n    self.window.mainloop()\r\n  File \"/home/cpl/venv_ceed/lib/python3.8/site-packages/kivy/core/window/window_sdl2.py\", line 701, in mainloop\r\n    if self.dispatch('on_key_down', key,\r\n  File \"kivy/_event.pyx\", line 715, in kivy._event.EventDispatcher.dispatch\r\n  File \"kivy/_event.pyx\", line 1295, in kivy._event.EventObservers.dispatch\r\n  File \"kivy/_event.pyx\", line 1219, in kivy._event.EventObservers._dispatch\r\n  File \"/home/cpl/venv_ceed/lib/python3.8/site-packages/kivy/core/window/__init__.py\", line 162, in _on_window_key_down\r\n    return self.dispatch('on_key_down', keycode, text, modifiers)\r\n  File \"kivy/_event.pyx\", line 715, in kivy._event.EventDispatcher.dispatch\r\n  File \"kivy/_event.pyx\", line 1295, in kivy._event.EventObservers.dispatch\r\n  File \"kivy/_event.pyx\", line 1219, in kivy._event.EventObservers._dispatch\r\n  File \"/home/cpl/venv_ceed/ceed/ceed/graphics/__init__.py\", line 50, in keyboard_on_key_down\r\n    return super(ShowMoreSelection, self).keyboard_on_key_down(\r\n  File \"/home/cpl/venv_ceed/ceed/ceed/graphics/__init__.py\", line 145, in keyboard_on_key_down\r\n    if super(WidgetList, self).keyboard_on_key_down(\r\n  File \"/home/cpl/venv_ceed/lib/python3.8/site-packages/kivy/uix/behaviors/focus.py\", line 534, in keyboard_on_key_down\r\n    if {'ctrl', 'alt', 'meta', 'super', 'compose'} & modifiers:\r\nTypeError: unsupported operand type(s) for &: 'set' and 'ObservableList'\r\n```\r\n\r\nThis should fix it.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/6954",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/6954/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/6954/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/6954/events",
        "html_url": "https://github.com/kivy/kivy/pull/6954",
        "id": 641363457,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDM2NjA0NzI2",
        "number": 6954,
        "title": "Network: Ignore ca_file on http scheme, fixes #6946",
        "user": {
            "login": "AndreMiras",
            "id": 24973,
            "node_id": "MDQ6VXNlcjI0OTcz",
            "avatar_url": "https://avatars.githubusercontent.com/u/24973?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/AndreMiras",
            "html_url": "https://github.com/AndreMiras",
            "followers_url": "https://api.github.com/users/AndreMiras/followers",
            "following_url": "https://api.github.com/users/AndreMiras/following{/other_user}",
            "gists_url": "https://api.github.com/users/AndreMiras/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/AndreMiras/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/AndreMiras/subscriptions",
            "organizations_url": "https://api.github.com/users/AndreMiras/orgs",
            "repos_url": "https://api.github.com/users/AndreMiras/repos",
            "events_url": "https://api.github.com/users/AndreMiras/events{/privacy}",
            "received_events_url": "https://api.github.com/users/AndreMiras/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 2462294619,
                "node_id": "MDU6TGFiZWwyNDYyMjk0NjE5",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Component:%20Misc",
                "name": "Component: Misc",
                "color": "87edb5",
                "default": false,
                "description": "compat, cache, tools, network, etc."
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": {
            "url": "https://api.github.com/repos/kivy/kivy/milestones/26",
            "html_url": "https://github.com/kivy/kivy/milestone/26",
            "labels_url": "https://api.github.com/repos/kivy/kivy/milestones/26/labels",
            "id": 1075858,
            "node_id": "MDk6TWlsZXN0b25lMTA3NTg1OA==",
            "number": 26,
            "title": "2.0.0",
            "description": "",
            "creator": {
                "login": "dessant",
                "id": 7513068,
                "node_id": "MDQ6VXNlcjc1MTMwNjg=",
                "avatar_url": "https://avatars.githubusercontent.com/u/7513068?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/dessant",
                "html_url": "https://github.com/dessant",
                "followers_url": "https://api.github.com/users/dessant/followers",
                "following_url": "https://api.github.com/users/dessant/following{/other_user}",
                "gists_url": "https://api.github.com/users/dessant/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/dessant/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dessant/subscriptions",
                "organizations_url": "https://api.github.com/users/dessant/orgs",
                "repos_url": "https://api.github.com/users/dessant/repos",
                "events_url": "https://api.github.com/users/dessant/events{/privacy}",
                "received_events_url": "https://api.github.com/users/dessant/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 0,
            "closed_issues": 323,
            "state": "closed",
            "created_at": "2015-04-20T19:06:41Z",
            "updated_at": "2020-12-11T23:16:36Z",
            "due_on": null,
            "closed_at": "2020-12-09T21:18:05Z"
        },
        "comments": 0,
        "created_at": "2020-06-18T16:28:20Z",
        "updated_at": "2020-12-09T08:17:12Z",
        "closed_at": "2020-06-18T18:44:13Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/6954",
            "html_url": "https://github.com/kivy/kivy/pull/6954",
            "diff_url": "https://github.com/kivy/kivy/pull/6954.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/6954.patch"
        },
        "body": "Don't pass a `context` keyword argument for `HTTPConnection`.\r\nThe error was:\r\n```\r\n TypeError: __init__() got an unexpected keyword argument 'context'\r\n ```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5990",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5990/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5990/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5990/events",
        "html_url": "https://github.com/kivy/kivy/pull/5990",
        "id": 369090589,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjIyMTEzNjM0",
        "number": 5990,
        "title": "[test][highlight]Fix unittest error when using pytest",
        "user": {
            "login": "Fak3",
            "id": 991641,
            "node_id": "MDQ6VXNlcjk5MTY0MQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/991641?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Fak3",
            "html_url": "https://github.com/Fak3",
            "followers_url": "https://api.github.com/users/Fak3/followers",
            "following_url": "https://api.github.com/users/Fak3/following{/other_user}",
            "gists_url": "https://api.github.com/users/Fak3/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Fak3/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Fak3/subscriptions",
            "organizations_url": "https://api.github.com/users/Fak3/orgs",
            "repos_url": "https://api.github.com/users/Fak3/repos",
            "events_url": "https://api.github.com/users/Fak3/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Fak3/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-10-11T12:10:05Z",
        "updated_at": "2019-05-23T03:16:53Z",
        "closed_at": "2018-10-11T14:11:07Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5990",
            "html_url": "https://github.com/kivy/kivy/pull/5990",
            "diff_url": "https://github.com/kivy/kivy/pull/5990.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5990.patch"
        },
        "body": "When you write GraphicUnitTest and attempt to launch it with pytest, the error occurs:\r\n```\r\n    def __call__(self, *args, **kwds):\r\n>       return self.run(*args, **kwds)\r\nE       TypeError: run() got an unexpected keyword argument 'result'\r\n/usr/lib64/python3.6/unittest/case.py:653: TypeError\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/6291",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/6291/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/6291/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/6291/events",
        "html_url": "https://github.com/kivy/kivy/pull/6291",
        "id": 440359784,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjc1OTQyMTk3",
        "number": 6291,
        "title": "[widgets/tabbedpanel]Fix bug in TabbedPanel.remove_widget method",
        "user": {
            "login": "pythonic64",
            "id": 9366353,
            "node_id": "MDQ6VXNlcjkzNjYzNTM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9366353?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pythonic64",
            "html_url": "https://github.com/pythonic64",
            "followers_url": "https://api.github.com/users/pythonic64/followers",
            "following_url": "https://api.github.com/users/pythonic64/following{/other_user}",
            "gists_url": "https://api.github.com/users/pythonic64/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pythonic64/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pythonic64/subscriptions",
            "organizations_url": "https://api.github.com/users/pythonic64/orgs",
            "repos_url": "https://api.github.com/users/pythonic64/repos",
            "events_url": "https://api.github.com/users/pythonic64/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pythonic64/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-05-04T19:12:12Z",
        "updated_at": "2019-05-22T20:00:38Z",
        "closed_at": "2019-05-04T23:48:48Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/6291",
            "html_url": "https://github.com/kivy/kivy/pull/6291",
            "diff_url": "https://github.com/kivy/kivy/pull/6291.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/6291.patch"
        },
        "body": "Attribute `_childrens` of `TabbedPanel` is a `list` and calling `pop` method with two arguments would raise a `TypeError`. Request fixes this bug by calling `remove` method.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/6175",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/6175/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/6175/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/6175/events",
        "html_url": "https://github.com/kivy/kivy/pull/6175",
        "id": 416402931,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjU3NjY4NTYx",
        "number": 6175,
        "title": "[base/utils]kivy.utils.rgba function bug fix for python 3 (used to crash)",
        "user": {
            "login": "ShaiAvr",
            "id": 35605235,
            "node_id": "MDQ6VXNlcjM1NjA1MjM1",
            "avatar_url": "https://avatars.githubusercontent.com/u/35605235?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ShaiAvr",
            "html_url": "https://github.com/ShaiAvr",
            "followers_url": "https://api.github.com/users/ShaiAvr/followers",
            "following_url": "https://api.github.com/users/ShaiAvr/following{/other_user}",
            "gists_url": "https://api.github.com/users/ShaiAvr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ShaiAvr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ShaiAvr/subscriptions",
            "organizations_url": "https://api.github.com/users/ShaiAvr/orgs",
            "repos_url": "https://api.github.com/users/ShaiAvr/repos",
            "events_url": "https://api.github.com/users/ShaiAvr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ShaiAvr/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2019-03-02T14:33:56Z",
        "updated_at": "2019-05-23T17:46:31Z",
        "closed_at": "2019-03-02T15:52:06Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/6175",
            "html_url": "https://github.com/kivy/kivy/pull/6175",
            "diff_url": "https://github.com/kivy/kivy/pull/6175.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/6175.patch"
        },
        "body": "I am working on a project with kivy on Windows 10 and Python 3.7.2 and I recently noticed that the `rgba` function from `kivy.utils` doesn't work on this version of python. It  simply crashes with this error message:\r\n```\r\nTraceback (most recent call last):\r\n   File \"test.py\", line 91, in <module>\r\n     print(ut.rgba([255, 255, 255]))\r\n   File \"D:\\Programs\\Python37\\lib\\site-packages\\kivy\\utils.py\", line 101, in rgba\r\n     if len(s) == 3:\r\n TypeError: object of type 'map' has no len()\r\n```\r\nWhen looking at the source code, I found what's the problem:\r\nIt's using the `map` function to parse the arguments. This function was changed in Python 3, and now it returns a generator (`map` object to be specific) instead of a `list` so the `len` function fails. I changed this code to use list comprehension instead of `map`, so now it works on both versions of python.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/6107",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/6107/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/6107/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/6107/events",
        "html_url": "https://github.com/kivy/kivy/pull/6107",
        "id": 401116468,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjQ2MTIwODE2",
        "number": 6107,
        "title": "[core/window]Fixed fullscreen and orientation handling to work with SDL-2.0.9 on Android",
        "user": {
            "login": "inclement",
            "id": 1265819,
            "node_id": "MDQ6VXNlcjEyNjU4MTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1265819?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/inclement",
            "html_url": "https://github.com/inclement",
            "followers_url": "https://api.github.com/users/inclement/followers",
            "following_url": "https://api.github.com/users/inclement/following{/other_user}",
            "gists_url": "https://api.github.com/users/inclement/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/inclement/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/inclement/subscriptions",
            "organizations_url": "https://api.github.com/users/inclement/orgs",
            "repos_url": "https://api.github.com/users/inclement/repos",
            "events_url": "https://api.github.com/users/inclement/events{/privacy}",
            "received_events_url": "https://api.github.com/users/inclement/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 4,
        "created_at": "2019-01-20T16:54:46Z",
        "updated_at": "2019-05-23T04:42:50Z",
        "closed_at": "2019-01-24T22:13:05Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/6107",
            "html_url": "https://github.com/kivy/kivy/pull/6107",
            "diff_url": "https://github.com/kivy/kivy/pull/6107.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/6107.patch"
        },
        "body": "Makes Kivy compatible with python-for-android after the changes in https://github.com/kivy/python-for-android/pull/1528.\r\n\r\nThis probably also fixes some bugs in reading the env vars in python2/python3, especially on iOS with python3.\r\n\r\nThe code here was a bit messy and could do with further improvement, but that's a more general Kivy issue.\r\n\r\nThere is still some problem with handling the back button. After pressing it so that the app closes, then re-opening the app, I get the following error:\r\n\r\n```\r\n01-20 16:49:16.435 18071 18160 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/net.inclem.lzviewer/files/app/.kivy/logs/kivy_19-01-20_1.txt\r\n01-20 16:49:16.435 18071 18160 I python  : [INFO   ] [Kivy        ] v1.11.0.dev0, git-12a8b13, 20190120\r\n01-20 16:49:16.435 18071 18160 I python  : [INFO   ] [Python      ] v3.7.1 (default, Jan 18 2019, 23:21:04) \r\n01-20 16:49:16.435 18071 18160 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55\r\n01-20 16:49:16.669 18071 18160 I python  :  Traceback (most recent call last):\r\n01-20 16:49:16.669 18071 18160 I python  :    File \"main.py\", line 14, in <module>\r\n01-20 16:49:16.670 18071 18160 I python  :      from kivy.app import App\r\n01-20 16:49:16.670 18071 18160 I python  :    File \"/data/user/0/net.inclem.lzviewer/files/app/_python_bundle/site-packages/kivy/app.py\", line 319, in <module>\r\n01-20 16:49:16.671 18071 18160 I python  :      from kivy.base import runTouchApp, stopTouchApp\r\n01-20 16:49:16.672 18071 18160 I python  :    File \"/data/user/0/net.inclem.lzviewer/files/app/_python_bundle/site-packages/kivy/base.py\", line 26, in <module>\r\n01-20 16:49:16.672 18071 18160 I python  :      from kivy.clock import Clock\r\n01-20 16:49:16.672 18071 18160 I python  :    File \"/data/user/0/net.inclem.lzviewer/files/app/_python_bundle/site-packages/kivy/clock.py\", line 706, in <module>\r\n01-20 16:49:16.674 18071 18160 I python  :      class ClockBase(ClockBaseBehavior, CyClockBase):\r\n01-20 16:49:16.675 18071 18160 I python  :  TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases\r\n01-20 16:49:16.861 18071 18160 I python  : Python for android ended.\r\n```\r\nI haven't yet checked if this is related to the SDL_ANDROID_TRAP_BACK_BUTTON hint, which I don't think I have set. It's a weird error though, the Python thread appears to finish and close just fine so I don't see what state is hanging around to cause this problem. The issue goes away if the app is completely closed by swiping it away in the app list.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5678",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5678/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5678/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5678/events",
        "html_url": "https://github.com/kivy/kivy/pull/5678",
        "id": 309387060,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTc4MDU0MDYz",
        "number": 5678,
        "title": "Fix TypeError when Trackball devices are used",
        "user": {
            "login": "DefaultUser",
            "id": 1263275,
            "node_id": "MDQ6VXNlcjEyNjMyNzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1263275?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/DefaultUser",
            "html_url": "https://github.com/DefaultUser",
            "followers_url": "https://api.github.com/users/DefaultUser/followers",
            "following_url": "https://api.github.com/users/DefaultUser/following{/other_user}",
            "gists_url": "https://api.github.com/users/DefaultUser/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/DefaultUser/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/DefaultUser/subscriptions",
            "organizations_url": "https://api.github.com/users/DefaultUser/orgs",
            "repos_url": "https://api.github.com/users/DefaultUser/repos",
            "events_url": "https://api.github.com/users/DefaultUser/events{/privacy}",
            "received_events_url": "https://api.github.com/users/DefaultUser/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "KeyWeeUsr",
            "id": 8825439,
            "node_id": "MDQ6VXNlcjg4MjU0Mzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8825439?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/KeyWeeUsr",
            "html_url": "https://github.com/KeyWeeUsr",
            "followers_url": "https://api.github.com/users/KeyWeeUsr/followers",
            "following_url": "https://api.github.com/users/KeyWeeUsr/following{/other_user}",
            "gists_url": "https://api.github.com/users/KeyWeeUsr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/KeyWeeUsr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/KeyWeeUsr/subscriptions",
            "organizations_url": "https://api.github.com/users/KeyWeeUsr/orgs",
            "repos_url": "https://api.github.com/users/KeyWeeUsr/repos",
            "events_url": "https://api.github.com/users/KeyWeeUsr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/KeyWeeUsr/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "KeyWeeUsr",
                "id": 8825439,
                "node_id": "MDQ6VXNlcjg4MjU0Mzk=",
                "avatar_url": "https://avatars.githubusercontent.com/u/8825439?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/KeyWeeUsr",
                "html_url": "https://github.com/KeyWeeUsr",
                "followers_url": "https://api.github.com/users/KeyWeeUsr/followers",
                "following_url": "https://api.github.com/users/KeyWeeUsr/following{/other_user}",
                "gists_url": "https://api.github.com/users/KeyWeeUsr/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/KeyWeeUsr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/KeyWeeUsr/subscriptions",
                "organizations_url": "https://api.github.com/users/KeyWeeUsr/orgs",
                "repos_url": "https://api.github.com/users/KeyWeeUsr/repos",
                "events_url": "https://api.github.com/users/KeyWeeUsr/events{/privacy}",
                "received_events_url": "https://api.github.com/users/KeyWeeUsr/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 1,
        "created_at": "2018-03-28T14:17:29Z",
        "updated_at": "2018-05-21T17:16:33Z",
        "closed_at": "2018-05-21T17:16:30Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5678",
            "html_url": "https://github.com/kivy/kivy/pull/5678",
            "diff_url": "https://github.com/kivy/kivy/pull/5678.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5678.patch"
        },
        "body": "Fixes crashes whenever a ``pygame.JOYBALLMOTION`` or ``SDL_JOYBALLMOTION`` event happens. Both window_pygame.py https://github.com/kivy/kivy/blob/3a2a86ce71c6c2806b9d3c2ee39f95ef4131ffa1/kivy/core/window/window_pygame.py#L349-L350 and window_sdl2.py https://github.com/kivy/kivy/blob/3a2a86ce71c6c2806b9d3c2ee39f95ef4131ffa1/kivy/core/window/window_sdl2.py#L539 call this method with two position values",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5715",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5715/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5715/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5715/events",
        "html_url": "https://github.com/kivy/kivy/pull/5715",
        "id": 318648297,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTg0NzkzMjYx",
        "number": 5715,
        "title": "Let Layout.add_widget use the ``canvas`` argument",
        "user": {
            "login": "LogicalDash",
            "id": 1334358,
            "node_id": "MDQ6VXNlcjEzMzQzNTg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1334358?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/LogicalDash",
            "html_url": "https://github.com/LogicalDash",
            "followers_url": "https://api.github.com/users/LogicalDash/followers",
            "following_url": "https://api.github.com/users/LogicalDash/following{/other_user}",
            "gists_url": "https://api.github.com/users/LogicalDash/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/LogicalDash/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/LogicalDash/subscriptions",
            "organizations_url": "https://api.github.com/users/LogicalDash/orgs",
            "repos_url": "https://api.github.com/users/LogicalDash/repos",
            "events_url": "https://api.github.com/users/LogicalDash/events{/privacy}",
            "received_events_url": "https://api.github.com/users/LogicalDash/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 67794,
                "node_id": "MDU6TGFiZWw2Nzc5NA==",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Component:%20core-providers",
                "name": "Component: core-providers",
                "color": "87edb5",
                "default": false,
                "description": "kivy/core"
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2018-04-28T16:06:21Z",
        "updated_at": "2018-06-30T07:33:46Z",
        "closed_at": "2018-05-05T19:02:01Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5715",
            "html_url": "https://github.com/kivy/kivy/pull/5715",
            "diff_url": "https://github.com/kivy/kivy/pull/5715.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5715.patch"
        },
        "body": "I had occasion to turn a Widget subclass of mine into a Layout, which caused TypeError as Layout's add_widget never got the ``canvas`` argument that base Widget has. Layout.add_widget isn't that different from Widget.add_widget though, so I just added it. Might help somebody?",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5577",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5577/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5577/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5577/events",
        "html_url": "https://github.com/kivy/kivy/pull/5577",
        "id": 289084142,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTYzMzA4NTAx",
        "number": 5577,
        "title": " window_x11: fix python3 TypeError",
        "user": {
            "login": "jakogut",
            "id": 40163,
            "node_id": "MDQ6VXNlcjQwMTYz",
            "avatar_url": "https://avatars.githubusercontent.com/u/40163?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jakogut",
            "html_url": "https://github.com/jakogut",
            "followers_url": "https://api.github.com/users/jakogut/followers",
            "following_url": "https://api.github.com/users/jakogut/following{/other_user}",
            "gists_url": "https://api.github.com/users/jakogut/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jakogut/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jakogut/subscriptions",
            "organizations_url": "https://api.github.com/users/jakogut/orgs",
            "repos_url": "https://api.github.com/users/jakogut/repos",
            "events_url": "https://api.github.com/users/jakogut/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jakogut/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 67794,
                "node_id": "MDU6TGFiZWw2Nzc5NA==",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Component:%20core-providers",
                "name": "Component: core-providers",
                "color": "87edb5",
                "default": false,
                "description": "kivy/core"
            },
            {
                "id": 137217236,
                "node_id": "MDU6TGFiZWwxMzcyMTcyMzY=",
                "url": "https://api.github.com/repos/kivy/kivy/labels/Platform:%20Linux",
                "name": "Platform: Linux",
                "color": "000000",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2018-01-16T22:53:30Z",
        "updated_at": "2018-01-18T20:02:04Z",
        "closed_at": "2018-01-18T19:01:28Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5577",
            "html_url": "https://github.com/kivy/kivy/pull/5577",
            "diff_url": "https://github.com/kivy/kivy/pull/5577.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5577.patch"
        },
        "body": "Encode Window.title as byte-string before attempting to set the x11 window\r\ntitle. This avoids \"TypeError: expected bytes, str found\" when using the\r\nx11 window provider with Python 3.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5240",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5240/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5240/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5240/events",
        "html_url": "https://github.com/kivy/kivy/pull/5240",
        "id": 238421033,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTI3Mzg2NjA3",
        "number": 5240,
        "title": "Settings in example are faulty",
        "user": {
            "login": "verderten",
            "id": 29658928,
            "node_id": "MDQ6VXNlcjI5NjU4OTI4",
            "avatar_url": "https://avatars.githubusercontent.com/u/29658928?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/verderten",
            "html_url": "https://github.com/verderten",
            "followers_url": "https://api.github.com/users/verderten/followers",
            "following_url": "https://api.github.com/users/verderten/following{/other_user}",
            "gists_url": "https://api.github.com/users/verderten/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/verderten/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/verderten/subscriptions",
            "organizations_url": "https://api.github.com/users/verderten/orgs",
            "repos_url": "https://api.github.com/users/verderten/repos",
            "events_url": "https://api.github.com/users/verderten/events{/privacy}",
            "received_events_url": "https://api.github.com/users/verderten/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2017-06-26T01:19:08Z",
        "updated_at": "2017-07-21T23:39:27Z",
        "closed_at": "2017-07-21T23:39:27Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5240",
            "html_url": "https://github.com/kivy/kivy/pull/5240",
            "diff_url": "https://github.com/kivy/kivy/pull/5240.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5240.patch"
        },
        "body": "with \"true\": \"auto\" set\r\n\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/settings.py\", line 975, in add_json_panel\r\n     panel = self.create_json_panel(title, config, filename, data)\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/settings.py\", line 1015, in create_json_panel\r\n     instance = cls(panel=panel, **str_settings)\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/settings.py\", line 289, in __init__\r\n     super(SettingItem, self).__init__(**kwargs)\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/floatlayout.py\", line 65, in __init__\r\n     super(FloatLayout, self).__init__(**kwargs)\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/layout.py\", line 76, in __init__\r\n     super(Layout, self).__init__(**kwargs)\r\n   File \"/usr/local/lib/python3.6/dist-packages/kivy/uix/widget.py\", line 337, in __init__\r\n     super(Widget, self).__init__(**kwargs)\r\n   File \"kivy/_event.pyx\", line 254, in kivy._event.EventDispatcher.__init__ (/tmp/pycharm-packaging393/Kivy/kivy/_event.c:5332)\r\n TypeError: object.__init__() takes no parameters\r\n\r\nwithout is working as expected\r\nalso there is nothing in docs about this parameter. Outdated?",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/5091",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/5091/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/5091/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/5091/events",
        "html_url": "https://github.com/kivy/kivy/pull/5091",
        "id": 218701453,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTEzNzgyMjI2",
        "number": 5091,
        "title": "Fix get_pixel_format for py3",
        "user": {
            "login": "KeyWeeUsr",
            "id": 8825439,
            "node_id": "MDQ6VXNlcjg4MjU0Mzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8825439?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/KeyWeeUsr",
            "html_url": "https://github.com/KeyWeeUsr",
            "followers_url": "https://api.github.com/users/KeyWeeUsr/followers",
            "following_url": "https://api.github.com/users/KeyWeeUsr/following{/other_user}",
            "gists_url": "https://api.github.com/users/KeyWeeUsr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/KeyWeeUsr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/KeyWeeUsr/subscriptions",
            "organizations_url": "https://api.github.com/users/KeyWeeUsr/orgs",
            "repos_url": "https://api.github.com/users/KeyWeeUsr/repos",
            "events_url": "https://api.github.com/users/KeyWeeUsr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/KeyWeeUsr/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2017-04-01T15:04:37Z",
        "updated_at": "2017-08-25T19:02:52Z",
        "closed_at": "2017-04-07T21:35:46Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/5091",
            "html_url": "https://github.com/kivy/kivy/pull/5091",
            "diff_url": "https://github.com/kivy/kivy/pull/5091.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/5091.patch"
        },
        "body": "closes #5072 \r\n\r\nI haven't compiled it, because with my luck I'll cripple my environment in the process, but I've tried with the example from the issue and you can see that a part of cpdefed method raises an error. Put at the end of `on_touch_down`'s method this (with imports from `opengl.pyx` `glReadPixels`, and GL types):\r\n\r\n    print([ord(i) for i in glReadPixels(touch.x, touch.y, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE)])\r\n\r\nhappilly throws an error, which for some reason is silenced within Cython code (_this could be damn bad issue!_).\r\n\r\n    TypeError: ord() expected string of length 1, but int found\r\n\r\nThe fix is basically a check for python and ignoring `ord()` as the bytearray in py3 already consists of integers (therefore conversion isn't desired). Tested with:\r\n\r\n    from kivy.compat import PY2\r\n    print([ord(i) if PY2 else i for i in glReadPixels(\r\n          touch.x, touch.y, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE)])\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/4615",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/4615/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/4615/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/4615/events",
        "html_url": "https://github.com/kivy/kivy/pull/4615",
        "id": 177821612,
        "node_id": "MDExOlB1bGxSZXF1ZXN0ODU4MTg3ODE=",
        "number": 4615,
        "title": "Kv Lang: fix profiling tool HTML output generation",
        "user": {
            "login": "rafalo1333",
            "id": 7304986,
            "node_id": "MDQ6VXNlcjczMDQ5ODY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7304986?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rafalo1333",
            "html_url": "https://github.com/rafalo1333",
            "followers_url": "https://api.github.com/users/rafalo1333/followers",
            "following_url": "https://api.github.com/users/rafalo1333/following{/other_user}",
            "gists_url": "https://api.github.com/users/rafalo1333/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rafalo1333/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rafalo1333/subscriptions",
            "organizations_url": "https://api.github.com/users/rafalo1333/orgs",
            "repos_url": "https://api.github.com/users/rafalo1333/repos",
            "events_url": "https://api.github.com/users/rafalo1333/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rafalo1333/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-09-19T15:47:13Z",
        "updated_at": "2016-09-28T01:05:02Z",
        "closed_at": "2016-09-28T01:05:02Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/4615",
            "html_url": "https://github.com/kivy/kivy/pull/4615",
            "diff_url": "https://github.com/kivy/kivy/pull/4615.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/4615.patch"
        },
        "body": "Fixes `TypeError: coercing to Unicode: need string or buffer, NoneType found` error during HTML output generation. Skips one loop iteration if the file cant be opened.\n\nWorks like a charm for me and I believe it's better way of handling file than None check. Tool can encounter various problems while handling files and try/except is the most reliable solution in my opinion.\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/4109",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/4109/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/4109/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/4109/events",
        "html_url": "https://github.com/kivy/kivy/pull/4109",
        "id": 142235203,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjM1MTU2MjM=",
        "number": 4109,
        "title": "keyboard patch",
        "user": {
            "login": "weihuang0908",
            "id": 8722897,
            "node_id": "MDQ6VXNlcjg3MjI4OTc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8722897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/weihuang0908",
            "html_url": "https://github.com/weihuang0908",
            "followers_url": "https://api.github.com/users/weihuang0908/followers",
            "following_url": "https://api.github.com/users/weihuang0908/following{/other_user}",
            "gists_url": "https://api.github.com/users/weihuang0908/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/weihuang0908/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weihuang0908/subscriptions",
            "organizations_url": "https://api.github.com/users/weihuang0908/orgs",
            "repos_url": "https://api.github.com/users/weihuang0908/repos",
            "events_url": "https://api.github.com/users/weihuang0908/events{/privacy}",
            "received_events_url": "https://api.github.com/users/weihuang0908/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-03-21T01:55:17Z",
        "updated_at": "2016-03-25T14:17:47Z",
        "closed_at": "2016-03-25T14:17:47Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/4109",
            "html_url": "https://github.com/kivy/kivy/pull/4109",
            "diff_url": "https://github.com/kivy/kivy/pull/4109.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/4109.patch"
        },
        "body": "```\n issues#3853: Select dock mode, restart the app, press Continue and select one of the keyboard layouts, then use the docked keyboard.\n\nTypeError: key_up() takes exactly 3 arguments (5 given)\n\n# (<kivy.uix.vkeyboard.VKeyboard object at 0x10ae9c8a0>, u'g', u'g', [])\n# or (keyboard, keycode, text, modifiers)\n```\n\nThe crash can be avoided simply by appending a parameter for the function key_up\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/kivy/kivy/issues/4106",
        "repository_url": "https://api.github.com/repos/kivy/kivy",
        "labels_url": "https://api.github.com/repos/kivy/kivy/issues/4106/labels{/name}",
        "comments_url": "https://api.github.com/repos/kivy/kivy/issues/4106/comments",
        "events_url": "https://api.github.com/repos/kivy/kivy/issues/4106/events",
        "html_url": "https://github.com/kivy/kivy/pull/4106",
        "id": 142150052,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjM0OTIyMjM=",
        "number": 4106,
        "title": "Fix for shader editor example crash when editing on python 2",
        "user": {
            "login": "andong777",
            "id": 3743928,
            "node_id": "MDQ6VXNlcjM3NDM5Mjg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3743928?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/andong777",
            "html_url": "https://github.com/andong777",
            "followers_url": "https://api.github.com/users/andong777/followers",
            "following_url": "https://api.github.com/users/andong777/following{/other_user}",
            "gists_url": "https://api.github.com/users/andong777/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/andong777/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/andong777/subscriptions",
            "organizations_url": "https://api.github.com/users/andong777/orgs",
            "repos_url": "https://api.github.com/users/andong777/repos",
            "events_url": "https://api.github.com/users/andong777/events{/privacy}",
            "received_events_url": "https://api.github.com/users/andong777/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2016-03-20T10:45:57Z",
        "updated_at": "2016-03-20T21:08:49Z",
        "closed_at": "2016-03-20T21:08:37Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/kivy/kivy/pulls/4106",
            "html_url": "https://github.com/kivy/kivy/pull/4106",
            "diff_url": "https://github.com/kivy/kivy/pull/4106.diff",
            "patch_url": "https://github.com/kivy/kivy/pull/4106.patch"
        },
        "body": "The example shader editor crashed when editing on Python. The error is shown below.\n\n> TypeError: Expected str, got unicode\n\nIt is due to a mix of unicode and str. We can simply use str() to wrap the variable, like this:\n\n`fs = fs_header + str(self.fs)`\n\nIt works except for non-ascii chars. So I decide to use encode('utf-8') to do this.\n\n`fs = fs_header + self.fs.encode('utf-8')`\n\nI have tested it on Python 2.7 and Python 3.5.\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]