[
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/16120",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/16120/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/16120/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/16120/events",
        "html_url": "https://github.com/ray-project/ray/pull/16120",
        "id": 904079591,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjU1MjYxMjgy",
        "number": 16120,
        "title": "Revert \"Fix tracing bug when actors are defined before connecting to \u2026",
        "user": {
            "login": "ericl",
            "id": 14922,
            "node_id": "MDQ6VXNlcjE0OTIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/14922?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ericl",
            "html_url": "https://github.com/ericl",
            "followers_url": "https://api.github.com/users/ericl/followers",
            "following_url": "https://api.github.com/users/ericl/following{/other_user}",
            "gists_url": "https://api.github.com/users/ericl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ericl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ericl/subscriptions",
            "organizations_url": "https://api.github.com/users/ericl/orgs",
            "repos_url": "https://api.github.com/users/ericl/repos",
            "events_url": "https://api.github.com/users/ericl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ericl/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "simon-mo",
            "id": 21118851,
            "node_id": "MDQ6VXNlcjIxMTE4ODUx",
            "avatar_url": "https://avatars.githubusercontent.com/u/21118851?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/simon-mo",
            "html_url": "https://github.com/simon-mo",
            "followers_url": "https://api.github.com/users/simon-mo/followers",
            "following_url": "https://api.github.com/users/simon-mo/following{/other_user}",
            "gists_url": "https://api.github.com/users/simon-mo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/simon-mo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/simon-mo/subscriptions",
            "organizations_url": "https://api.github.com/users/simon-mo/orgs",
            "repos_url": "https://api.github.com/users/simon-mo/repos",
            "events_url": "https://api.github.com/users/simon-mo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/simon-mo/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "simon-mo",
                "id": 21118851,
                "node_id": "MDQ6VXNlcjIxMTE4ODUx",
                "avatar_url": "https://avatars.githubusercontent.com/u/21118851?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/simon-mo",
                "html_url": "https://github.com/simon-mo",
                "followers_url": "https://api.github.com/users/simon-mo/followers",
                "following_url": "https://api.github.com/users/simon-mo/following{/other_user}",
                "gists_url": "https://api.github.com/users/simon-mo/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/simon-mo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/simon-mo/subscriptions",
                "organizations_url": "https://api.github.com/users/simon-mo/orgs",
                "repos_url": "https://api.github.com/users/simon-mo/repos",
                "events_url": "https://api.github.com/users/simon-mo/events{/privacy}",
                "received_events_url": "https://api.github.com/users/simon-mo/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 2,
        "created_at": "2021-05-27T18:49:19Z",
        "updated_at": "2021-05-27T18:52:33Z",
        "closed_at": "2021-05-27T18:50:37Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/16120",
            "html_url": "https://github.com/ray-project/ray/pull/16120",
            "diff_url": "https://github.com/ray-project/ray/pull/16120.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/16120.patch"
        },
        "body": "\u2026cluster (#16069)\"\r\n\r\nThis reverts commit 6c1ea6661180e656e83e7e5835d362428654ad8d.\r\n\r\n```\r\n\r\n\r\n\r\nFile \"/ray/python/ray/util/tracing/tracing_helper.py\", line 279, in _function_with_tracing\r\n&nbsp; | return function(*args, **kwargs)\r\n&nbsp; | File \"/tmp/ray_cross_language_test/test_cross_language_invocation.py\", line 56, in py_func_call_java_actor\r\n&nbsp; | java_actor = c.remote(b\"Counter\")\r\n&nbsp; | File \"/ray/python/ray/actor.py\", line 418, in remote\r\n&nbsp; | return self._remote(args=args, kwargs=kwargs)\r\n&nbsp; | File \"/ray/python/ray/util/tracing/tracing_helper.py\", line 317, in _invocation_actor_class_remote_span\r\n&nbsp; | return method(self, args, kwargs, *_args, **_kwargs)\r\n&nbsp; | File \"/ray/python/ray/actor.py\", line 698, in _remote\r\n&nbsp; | creation_args = cross_language.format_args(worker, args, kwargs)\r\n&nbsp; | File \"/ray/python/ray/cross_language.py\", line 29, in format_args\r\n&nbsp; | raise TypeError(\"Cross language remote functions \"\r\n&nbsp; | TypeError: Cross language remote functions does not support kwargs.\r\n&nbsp;\r\n\r\n<br class=\"Apple-interchange-newline\">\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/15426",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/15426/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/15426/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/15426/events",
        "html_url": "https://github.com/ray-project/ray/pull/15426",
        "id": 863239131,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjE5NjgzNzk5",
        "number": 15426,
        "title": "Fix restore_spilled_objects() for external object spilling",
        "user": {
            "login": "franklsf95",
            "id": 2411818,
            "node_id": "MDQ6VXNlcjI0MTE4MTg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2411818?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/franklsf95",
            "html_url": "https://github.com/franklsf95",
            "followers_url": "https://api.github.com/users/franklsf95/followers",
            "following_url": "https://api.github.com/users/franklsf95/following{/other_user}",
            "gists_url": "https://api.github.com/users/franklsf95/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/franklsf95/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/franklsf95/subscriptions",
            "organizations_url": "https://api.github.com/users/franklsf95/orgs",
            "repos_url": "https://api.github.com/users/franklsf95/repos",
            "events_url": "https://api.github.com/users/franklsf95/events{/privacy}",
            "received_events_url": "https://api.github.com/users/franklsf95/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2021-04-20T21:02:07Z",
        "updated_at": "2021-04-20T23:34:17Z",
        "closed_at": "2021-04-20T23:33:45Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/15426",
            "html_url": "https://github.com/ray-project/ray/pull/15426",
            "diff_url": "https://github.com/ray-project/ray/pull/15426.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/15426.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\ncc @stephanie-wang @rkooo567 \r\n\r\n## Why are these changes needed?\r\n\r\nBefore, the Python worker would throw\r\n\r\n```\r\n2021-04-20 13:52:03,632 WARNING worker.py:1086 -- Traceback (most recent call last):\r\n  File \"python/ray/_raylet.pyx\", line 716, in ray._raylet.restore_spilled_objects_handler\r\n  File \"python/ray/_raylet.pyx\", line 719, in ray._raylet.restore_spilled_objects_handler\r\n  File \"/home/ubuntu/raydev/ray/python/ray/external_storage.py\", line 514, in restore_spilled_objects\r\n    return _external_storage.restore_spilled_objects(object_refs,\r\n  File \"/home/ubuntu/raydev/ray/python/ray/external_storage.py\", line 423, in restore_spilled_objects\r\n    self._size_check(metadata_len, buf_len, parsed_result.size)\r\nTypeError: _size_check() missing 1 required positional argument: 'obtained_data_size'\r\n```\r\n\r\nThis fixes the error.\r\n\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\n\r\n## Related issue number\r\n\r\n<!-- For example: \"Closes #1234\" -->\r\nFixes the error in #14948. Object spilling doesn't work fully correctly due to #14788, which will be fixed later.\r\n\r\n## Checks\r\n\r\n- [x] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/14378",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/14378/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/14378/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/14378/events",
        "html_url": "https://github.com/ray-project/ray/pull/14378",
        "id": 817051138,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTgwNjA4OTc3",
        "number": 14378,
        "title": "[Dashboard] Fix reporter agent",
        "user": {
            "login": "fyrestone",
            "id": 6308809,
            "node_id": "MDQ6VXNlcjYzMDg4MDk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6308809?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fyrestone",
            "html_url": "https://github.com/fyrestone",
            "followers_url": "https://api.github.com/users/fyrestone/followers",
            "following_url": "https://api.github.com/users/fyrestone/following{/other_user}",
            "gists_url": "https://api.github.com/users/fyrestone/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fyrestone/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fyrestone/subscriptions",
            "organizations_url": "https://api.github.com/users/fyrestone/orgs",
            "repos_url": "https://api.github.com/users/fyrestone/repos",
            "events_url": "https://api.github.com/users/fyrestone/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fyrestone/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 1123469783,
                "node_id": "MDU6TGFiZWwxMTIzNDY5Nzgz",
                "url": "https://api.github.com/repos/ray-project/ray/labels/@tests-ok",
                "name": "@tests-ok",
                "color": "cdef6e",
                "default": false,
                "description": "The tagger certifies test failures are unrelated and assumes personal liability."
            },
            {
                "id": 2090554708,
                "node_id": "MDU6TGFiZWwyMDkwNTU0NzA4",
                "url": "https://api.github.com/repos/ray-project/ray/labels/dashboard",
                "name": "dashboard",
                "color": "BFDADC",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "edoakes",
            "id": 9871461,
            "node_id": "MDQ6VXNlcjk4NzE0NjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9871461?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/edoakes",
            "html_url": "https://github.com/edoakes",
            "followers_url": "https://api.github.com/users/edoakes/followers",
            "following_url": "https://api.github.com/users/edoakes/following{/other_user}",
            "gists_url": "https://api.github.com/users/edoakes/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/edoakes/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/edoakes/subscriptions",
            "organizations_url": "https://api.github.com/users/edoakes/orgs",
            "repos_url": "https://api.github.com/users/edoakes/repos",
            "events_url": "https://api.github.com/users/edoakes/events{/privacy}",
            "received_events_url": "https://api.github.com/users/edoakes/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "edoakes",
                "id": 9871461,
                "node_id": "MDQ6VXNlcjk4NzE0NjE=",
                "avatar_url": "https://avatars.githubusercontent.com/u/9871461?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/edoakes",
                "html_url": "https://github.com/edoakes",
                "followers_url": "https://api.github.com/users/edoakes/followers",
                "following_url": "https://api.github.com/users/edoakes/following{/other_user}",
                "gists_url": "https://api.github.com/users/edoakes/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/edoakes/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/edoakes/subscriptions",
                "organizations_url": "https://api.github.com/users/edoakes/orgs",
                "repos_url": "https://api.github.com/users/edoakes/repos",
                "events_url": "https://api.github.com/users/edoakes/events{/privacy}",
                "received_events_url": "https://api.github.com/users/edoakes/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "kathryn-zhou",
                "id": 52860192,
                "node_id": "MDQ6VXNlcjUyODYwMTky",
                "avatar_url": "https://avatars.githubusercontent.com/u/52860192?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kathryn-zhou",
                "html_url": "https://github.com/kathryn-zhou",
                "followers_url": "https://api.github.com/users/kathryn-zhou/followers",
                "following_url": "https://api.github.com/users/kathryn-zhou/following{/other_user}",
                "gists_url": "https://api.github.com/users/kathryn-zhou/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kathryn-zhou/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kathryn-zhou/subscriptions",
                "organizations_url": "https://api.github.com/users/kathryn-zhou/orgs",
                "repos_url": "https://api.github.com/users/kathryn-zhou/repos",
                "events_url": "https://api.github.com/users/kathryn-zhou/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kathryn-zhou/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 6,
        "created_at": "2021-02-26T05:24:39Z",
        "updated_at": "2021-03-18T06:49:36Z",
        "closed_at": "2021-03-08T19:12:34Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/14378",
            "html_url": "https://github.com/ray-project/ray/pull/14378",
            "diff_url": "https://github.com/ray-project/ray/pull/14378.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/14378.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\n- Problem\r\n  - The `ReporterAgent._record_stats` may raises exception due to\r\n    - the use of local variables referenced before assignment.\r\n    - The `raylet_stats` may be an empty list, then access the key of `raylet_stats` will raise `TypeError: list indices must be integers or slices, not str`.\r\n- Solution\r\n  - Add metric record to `records_reported` if the record object is generated.\r\n- Other\r\n  - Add a `_get_raylet_proc()` method to get raylet proc object, returns None is the raylet proc is not available.\r\n\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\n\r\n<!-- For example: \"Closes #1234\" -->\r\n\r\n## Checks\r\n\r\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/14698",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/14698/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/14698/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/14698/events",
        "html_url": "https://github.com/ray-project/ray/pull/14698",
        "id": 832389736,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTkzNTU0NDQz",
        "number": 14698,
        "title": "[client] Fix serialization of RayTaskError",
        "user": {
            "login": "richardliaw",
            "id": 4529381,
            "node_id": "MDQ6VXNlcjQ1MjkzODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/richardliaw",
            "html_url": "https://github.com/richardliaw",
            "followers_url": "https://api.github.com/users/richardliaw/followers",
            "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
            "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
            "organizations_url": "https://api.github.com/users/richardliaw/orgs",
            "repos_url": "https://api.github.com/users/richardliaw/repos",
            "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/richardliaw/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "ericl",
            "id": 14922,
            "node_id": "MDQ6VXNlcjE0OTIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/14922?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ericl",
            "html_url": "https://github.com/ericl",
            "followers_url": "https://api.github.com/users/ericl/followers",
            "following_url": "https://api.github.com/users/ericl/following{/other_user}",
            "gists_url": "https://api.github.com/users/ericl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ericl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ericl/subscriptions",
            "organizations_url": "https://api.github.com/users/ericl/orgs",
            "repos_url": "https://api.github.com/users/ericl/repos",
            "events_url": "https://api.github.com/users/ericl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ericl/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "ericl",
                "id": 14922,
                "node_id": "MDQ6VXNlcjE0OTIy",
                "avatar_url": "https://avatars.githubusercontent.com/u/14922?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ericl",
                "html_url": "https://github.com/ericl",
                "followers_url": "https://api.github.com/users/ericl/followers",
                "following_url": "https://api.github.com/users/ericl/following{/other_user}",
                "gists_url": "https://api.github.com/users/ericl/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ericl/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ericl/subscriptions",
                "organizations_url": "https://api.github.com/users/ericl/orgs",
                "repos_url": "https://api.github.com/users/ericl/repos",
                "events_url": "https://api.github.com/users/ericl/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ericl/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "AmeerHajAli",
                "id": 18361764,
                "node_id": "MDQ6VXNlcjE4MzYxNzY0",
                "avatar_url": "https://avatars.githubusercontent.com/u/18361764?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/AmeerHajAli",
                "html_url": "https://github.com/AmeerHajAli",
                "followers_url": "https://api.github.com/users/AmeerHajAli/followers",
                "following_url": "https://api.github.com/users/AmeerHajAli/following{/other_user}",
                "gists_url": "https://api.github.com/users/AmeerHajAli/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/AmeerHajAli/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/AmeerHajAli/subscriptions",
                "organizations_url": "https://api.github.com/users/AmeerHajAli/orgs",
                "repos_url": "https://api.github.com/users/AmeerHajAli/repos",
                "events_url": "https://api.github.com/users/AmeerHajAli/events{/privacy}",
                "received_events_url": "https://api.github.com/users/AmeerHajAli/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "ijrsvt",
                "id": 21353794,
                "node_id": "MDQ6VXNlcjIxMzUzNzk0",
                "avatar_url": "https://avatars.githubusercontent.com/u/21353794?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ijrsvt",
                "html_url": "https://github.com/ijrsvt",
                "followers_url": "https://api.github.com/users/ijrsvt/followers",
                "following_url": "https://api.github.com/users/ijrsvt/following{/other_user}",
                "gists_url": "https://api.github.com/users/ijrsvt/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ijrsvt/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ijrsvt/subscriptions",
                "organizations_url": "https://api.github.com/users/ijrsvt/orgs",
                "repos_url": "https://api.github.com/users/ijrsvt/repos",
                "events_url": "https://api.github.com/users/ijrsvt/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ijrsvt/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 1,
        "created_at": "2021-03-16T04:07:45Z",
        "updated_at": "2021-03-18T19:26:34Z",
        "closed_at": "2021-03-18T19:26:33Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/14698",
            "html_url": "https://github.com/ray-project/ray/pull/14698",
            "diff_url": "https://github.com/ray-project/ray/pull/14698.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/14698.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\n\r\nBefore:\r\n```\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-1-b34c9e83cb1f> in <module>\r\n     17\r\n     18 # grpc error\r\n---> 19 ray.get(g.remote())\r\n     20\r\n     21 # grpc error\r\n\r\n~/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)\r\n     44     def wrapper(*args, **kwargs):\r\n     45         if client_mode_should_convert():\r\n---> 46             return getattr(ray, func.__name__)(*args, **kwargs)\r\n     47         return func(*args, **kwargs)\r\n     48\r\n\r\n~/ray/python/ray/util/client/api.py in get(self, vals, timeout)\r\n     33             timeout: Optional timeout in milliseconds\r\n     34         \"\"\"\r\n---> 35         return self.worker.get(vals, timeout=timeout)\r\n     36\r\n     37     def put(self, *args, **kwargs):\r\n\r\n~/ray/python/ray/util/client/worker.py in get(self, vals, timeout)\r\n    194                     else:\r\n    195                         op_timeout = MAX_BLOCKING_OPERATION_TIME_S\r\n--> 196                     res = self._get(obj_ref, op_timeout)\r\n    197                     break\r\n    198                 except GetTimeoutError:\r\n\r\n~/ray/python/ray/util/client/worker.py in _get(self, ref, timeout)\r\n    213         if not data.valid:\r\n    214             try:\r\n--> 215                 err = cloudpickle.loads(data.error)\r\n    216             except pickle.UnpicklingError:\r\n    217                 logger.exception(\"Failed to deserialize {}\".format(data.error))\r\n\r\nTypeError: __init__() missing 1 required positional argument: 'cause'\r\n```\r\n\r\nAfter:\r\n```\r\nRayTaskError(PermissionError)             Traceback (most recent call last)\r\n<ipython-input-1-b34c9e83cb1f> in <module>\r\n     17\r\n     18 # grpc error\r\n---> 19 ray.get(g.remote())\r\n     20\r\n     21 # grpc error\r\n\r\n~/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)\r\n     44     def wrapper(*args, **kwargs):\r\n     45         if client_mode_should_convert():\r\n---> 46             return getattr(ray, func.__name__)(*args, **kwargs)\r\n     47         return func(*args, **kwargs)\r\n     48\r\n\r\n~/ray/python/ray/util/client/api.py in get(self, vals, timeout)\r\n     33             timeout: Optional timeout in milliseconds\r\n     34         \"\"\"\r\n---> 35         return self.worker.get(vals, timeout=timeout)\r\n     36\r\n     37     def put(self, *args, **kwargs):\r\n\r\n~/ray/python/ray/util/client/worker.py in get(self, vals, timeout)\r\n    194                     else:\r\n    195                         op_timeout = MAX_BLOCKING_OPERATION_TIME_S\r\n--> 196                     res = self._get(obj_ref, op_timeout)\r\n    197                     break\r\n    198                 except GetTimeoutError:\r\n\r\n~/ray/python/ray/util/client/worker.py in _get(self, ref, timeout)\r\n    217                 logger.exception(\"Failed to deserialize {}\".format(data.error))\r\n    218                 raise\r\n--> 219             raise err\r\n    220         return loads_from_server(data.data)\r\n    221\r\n\r\nRayTaskError(PermissionError): ray::g() (pid=5515, ip=192.168.1.115)\r\n  File \"python/ray/_raylet.pyx\", line 501, in ray._raylet.execute_task\r\n  File \"<ipython-input-1-b34c9e83cb1f>\", line 15, in g\r\nPermissionError: [Errno 1] Operation not permitted: '/dev/asdf'\r\n```\r\n## Related issue number\r\n\r\nCloses https://github.com/ray-project/ray/issues/13842, Closes https://github.com/ray-project/ray/issues/14172.\r\n\r\ncc @yuduber\r\n\r\n## Checks\r\n\r\n- [x] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [x] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/13039",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/13039/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/13039/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/13039/events",
        "html_url": "https://github.com/ray-project/ray/pull/13039",
        "id": 772988157,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTQ0MTU4NTcw",
        "number": 13039,
        "title": "[RLlib] Issue 13038: TorchPolicies: Accessing \"infos\" dict in train_batch causes `TypeError`.",
        "user": {
            "login": "sven1977",
            "id": 5839854,
            "node_id": "MDQ6VXNlcjU4Mzk4NTQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5839854?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sven1977",
            "html_url": "https://github.com/sven1977",
            "followers_url": "https://api.github.com/users/sven1977/followers",
            "following_url": "https://api.github.com/users/sven1977/following{/other_user}",
            "gists_url": "https://api.github.com/users/sven1977/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sven1977/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sven1977/subscriptions",
            "organizations_url": "https://api.github.com/users/sven1977/orgs",
            "repos_url": "https://api.github.com/users/sven1977/repos",
            "events_url": "https://api.github.com/users/sven1977/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sven1977/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "michaelzhiluo",
            "id": 20640975,
            "node_id": "MDQ6VXNlcjIwNjQwOTc1",
            "avatar_url": "https://avatars.githubusercontent.com/u/20640975?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/michaelzhiluo",
            "html_url": "https://github.com/michaelzhiluo",
            "followers_url": "https://api.github.com/users/michaelzhiluo/followers",
            "following_url": "https://api.github.com/users/michaelzhiluo/following{/other_user}",
            "gists_url": "https://api.github.com/users/michaelzhiluo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/michaelzhiluo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/michaelzhiluo/subscriptions",
            "organizations_url": "https://api.github.com/users/michaelzhiluo/orgs",
            "repos_url": "https://api.github.com/users/michaelzhiluo/repos",
            "events_url": "https://api.github.com/users/michaelzhiluo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/michaelzhiluo/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "michaelzhiluo",
                "id": 20640975,
                "node_id": "MDQ6VXNlcjIwNjQwOTc1",
                "avatar_url": "https://avatars.githubusercontent.com/u/20640975?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/michaelzhiluo",
                "html_url": "https://github.com/michaelzhiluo",
                "followers_url": "https://api.github.com/users/michaelzhiluo/followers",
                "following_url": "https://api.github.com/users/michaelzhiluo/following{/other_user}",
                "gists_url": "https://api.github.com/users/michaelzhiluo/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/michaelzhiluo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/michaelzhiluo/subscriptions",
                "organizations_url": "https://api.github.com/users/michaelzhiluo/orgs",
                "repos_url": "https://api.github.com/users/michaelzhiluo/repos",
                "events_url": "https://api.github.com/users/michaelzhiluo/events{/privacy}",
                "received_events_url": "https://api.github.com/users/michaelzhiluo/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-12-22T14:28:49Z",
        "updated_at": "2020-12-23T16:30:51Z",
        "closed_at": "2020-12-23T16:30:51Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/13039",
            "html_url": "https://github.com/ray-project/ray/pull/13039",
            "diff_url": "https://github.com/ray-project/ray/pull/13039.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/13039.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\nIssue #13038 \r\n\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\n\r\nIssue #13038 \r\n\r\n<!-- For example: \"Closes #1234\" -->\r\n\r\nIssue #13038 \r\n\r\n- [x] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [x] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/14126",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/14126/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/14126/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/14126/events",
        "html_url": "https://github.com/ray-project/ray/pull/14126",
        "id": 808994981,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTczOTMzOTQw",
        "number": 14126,
        "title": "Fix `assert get_outer_ref None` failed + Support better traceback.",
        "user": {
            "login": "rkooo567",
            "id": 18510752,
            "node_id": "MDQ6VXNlcjE4NTEwNzUy",
            "avatar_url": "https://avatars.githubusercontent.com/u/18510752?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rkooo567",
            "html_url": "https://github.com/rkooo567",
            "followers_url": "https://api.github.com/users/rkooo567/followers",
            "following_url": "https://api.github.com/users/rkooo567/following{/other_user}",
            "gists_url": "https://api.github.com/users/rkooo567/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rkooo567/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rkooo567/subscriptions",
            "organizations_url": "https://api.github.com/users/rkooo567/orgs",
            "repos_url": "https://api.github.com/users/rkooo567/repos",
            "events_url": "https://api.github.com/users/rkooo567/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rkooo567/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "stephanie-wang",
            "id": 2560516,
            "node_id": "MDQ6VXNlcjI1NjA1MTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2560516?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stephanie-wang",
            "html_url": "https://github.com/stephanie-wang",
            "followers_url": "https://api.github.com/users/stephanie-wang/followers",
            "following_url": "https://api.github.com/users/stephanie-wang/following{/other_user}",
            "gists_url": "https://api.github.com/users/stephanie-wang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stephanie-wang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stephanie-wang/subscriptions",
            "organizations_url": "https://api.github.com/users/stephanie-wang/orgs",
            "repos_url": "https://api.github.com/users/stephanie-wang/repos",
            "events_url": "https://api.github.com/users/stephanie-wang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stephanie-wang/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "stephanie-wang",
                "id": 2560516,
                "node_id": "MDQ6VXNlcjI1NjA1MTY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2560516?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stephanie-wang",
                "html_url": "https://github.com/stephanie-wang",
                "followers_url": "https://api.github.com/users/stephanie-wang/followers",
                "following_url": "https://api.github.com/users/stephanie-wang/following{/other_user}",
                "gists_url": "https://api.github.com/users/stephanie-wang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stephanie-wang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stephanie-wang/subscriptions",
                "organizations_url": "https://api.github.com/users/stephanie-wang/orgs",
                "repos_url": "https://api.github.com/users/stephanie-wang/repos",
                "events_url": "https://api.github.com/users/stephanie-wang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stephanie-wang/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "suquark",
                "id": 13750372,
                "node_id": "MDQ6VXNlcjEzNzUwMzcy",
                "avatar_url": "https://avatars.githubusercontent.com/u/13750372?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/suquark",
                "html_url": "https://github.com/suquark",
                "followers_url": "https://api.github.com/users/suquark/followers",
                "following_url": "https://api.github.com/users/suquark/following{/other_user}",
                "gists_url": "https://api.github.com/users/suquark/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/suquark/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/suquark/subscriptions",
                "organizations_url": "https://api.github.com/users/suquark/orgs",
                "repos_url": "https://api.github.com/users/suquark/repos",
                "events_url": "https://api.github.com/users/suquark/events{/privacy}",
                "received_events_url": "https://api.github.com/users/suquark/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 1,
        "created_at": "2021-02-16T05:24:50Z",
        "updated_at": "2021-02-16T18:09:02Z",
        "closed_at": "2021-02-16T18:09:02Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/14126",
            "html_url": "https://github.com/ray-project/ray/pull/14126",
            "diff_url": "https://github.com/ray-project/ray/pull/14126.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/14126.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\nThis PR is doing 2 things\r\n\r\nPreviously, if the `pickle.loads` called during deserialization failed, it failed silently (I assume the exception was caught somewhere and silently swallowed). After that since the next line which unset the outer ref wasn't called, in the subsequent call, it raised an exception. This also returns the system error object if the exception is generated from that code.\r\n\r\nThis also has a small refactoring to improve the readability of chained exception tasks. For example, suppose this scenario;\r\n```python3\r\nimport ray\r\n\r\nray.init()\r\n\r\n@ray.remote\r\ndef task(dep1, dep2):\r\n    return 3\r\n\r\n@ray.remote\r\ndef dep1():\r\n    raise ValueError(\"haha\")\r\n\r\n@ray.remote\r\ndef dep2():\r\n    raise TypeError(\"hoho\")\r\n\r\nprint(ray.get(task.remote(dep1.remote(), dep2.remote())))\r\n```\r\n\r\nthis previously printed \r\n```\r\nTraceback (most recent call last):\r\n  File \"exc.py\", line 17, in <module>\r\n    print(ray.get(task.remote(dep1.remote(), dep2.remote())))\r\n  File \"/Users/sangbincho/work/ray/python/ray/_private/client_mode_hook.py\", line 47, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/Users/sangbincho/work/ray/python/ray/worker.py\", line 1458, in get\r\n    raise value.as_instanceof_cause()\r\nray.exceptions.RayTaskError(ValueError): ray::task() (pid=93203, ip=192.168.1.3)\r\n  File \"python/ray/_raylet.pyx\", line 447, in ray._raylet.execute_task\r\n  File \"python/ray/_raylet.pyx\", line 468, in ray._raylet.execute_task\r\nray.exceptions.RayTaskError: ray::dep1() (pid=93203, ip=192.168.1.3)\r\n  File \"python/ray/_raylet.pyx\", line 490, in ray._raylet.execute_task\r\n  File \"exc.py\", line 11, in dep1\r\n    raise ValueError(\"haha\")\r\nValueError: haha\r\n```\r\nwhich is very confusing because we don't know what the line 468 is doing. But after this PR, it will be \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"exc.py\", line 17, in <module>\r\n    print(ray.get(task.remote(dep1.remote(), dep2.remote())))\r\n  File \"/Users/sangbincho/work/ray/python/ray/_private/client_mode_hook.py\", line 47, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/Users/sangbincho/work/ray/python/ray/worker.py\", line 1458, in get\r\n    raise value.as_instanceof_cause()\r\nray.exceptions.RayTaskError(ValueError): ray::task() (pid=93203, ip=192.168.1.3)\r\n  File \"python/ray/_raylet.pyx\", line 447, in ray._raylet.execute_task\r\n  File \"python/ray/_raylet.pyx\", line 468, in ray._raylet.execute_task\r\n  File \"python/ray/_raylet.pyx\", line 337, in ray._raylet.raise_if_dependency_failed\r\nray.exceptions.RayTaskError: ray::dep1() (pid=93203, ip=192.168.1.3)\r\n  File \"python/ray/_raylet.pyx\", line 490, in ray._raylet.execute_task\r\n  File \"exc.py\", line 11, in dep1\r\n    raise ValueError(\"haha\")\r\nValueError: haha\r\n```\r\nso that it is easier to understand the exception was caused by the dependency failure.\r\n\r\n## Related issue number\r\n\r\n<!-- For example: \"Closes #1234\" -->\r\n\r\n## Checks\r\n\r\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/11710",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/11710/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/11710/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/11710/events",
        "html_url": "https://github.com/ray-project/ray/pull/11710",
        "id": 732681355,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTEyNTg1MDY3",
        "number": 11710,
        "title": "[RLlib] Integration with SUMO Simulator",
        "user": {
            "login": "lcodeca",
            "id": 5700703,
            "node_id": "MDQ6VXNlcjU3MDA3MDM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5700703?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lcodeca",
            "html_url": "https://github.com/lcodeca",
            "followers_url": "https://api.github.com/users/lcodeca/followers",
            "following_url": "https://api.github.com/users/lcodeca/following{/other_user}",
            "gists_url": "https://api.github.com/users/lcodeca/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lcodeca/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lcodeca/subscriptions",
            "organizations_url": "https://api.github.com/users/lcodeca/orgs",
            "repos_url": "https://api.github.com/users/lcodeca/repos",
            "events_url": "https://api.github.com/users/lcodeca/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lcodeca/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "sven1977",
            "id": 5839854,
            "node_id": "MDQ6VXNlcjU4Mzk4NTQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5839854?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sven1977",
            "html_url": "https://github.com/sven1977",
            "followers_url": "https://api.github.com/users/sven1977/followers",
            "following_url": "https://api.github.com/users/sven1977/following{/other_user}",
            "gists_url": "https://api.github.com/users/sven1977/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sven1977/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sven1977/subscriptions",
            "organizations_url": "https://api.github.com/users/sven1977/orgs",
            "repos_url": "https://api.github.com/users/sven1977/repos",
            "events_url": "https://api.github.com/users/sven1977/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sven1977/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "sven1977",
                "id": 5839854,
                "node_id": "MDQ6VXNlcjU4Mzk4NTQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/5839854?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sven1977",
                "html_url": "https://github.com/sven1977",
                "followers_url": "https://api.github.com/users/sven1977/followers",
                "following_url": "https://api.github.com/users/sven1977/following{/other_user}",
                "gists_url": "https://api.github.com/users/sven1977/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sven1977/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sven1977/subscriptions",
                "organizations_url": "https://api.github.com/users/sven1977/orgs",
                "repos_url": "https://api.github.com/users/sven1977/repos",
                "events_url": "https://api.github.com/users/sven1977/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sven1977/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-10-29T21:38:10Z",
        "updated_at": "2021-01-08T01:46:40Z",
        "closed_at": "2020-11-03T08:45:03Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/11710",
            "html_url": "https://github.com/ray-project/ray/pull/11710",
            "diff_url": "https://github.com/ray-project/ray/pull/11710.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/11710.patch"
        },
        "body": "## Why are these changes needed?\r\n\r\nEclipse SUMO (Simulation of Urban MObility) is an open-source, highly portable, microscopic, and continuous multi-modal traffic simulation package designed to handle large networks. See: https://www.eclipse.org/sumo/\r\n\r\nThis PR integrates the RLLIB SUMO Utils library (https://github.com/lcodeca/rllibsumoutils) directly in RLLIB.\r\nIt provides: \r\n- `rllib/contrib/sumo` a generic connector between a user-defined environment and the SUMO simulator with additional utils.\r\n- `rllib/examples/simulators/sumo` and example of the multi-agent environment and a simple SUMO scenario\r\n- `rllib/examples/sumo_env_local.py` PPO Trainer (tune)\r\n\r\nThe integration was discussed with @sven1977 \r\n\r\n## Related issue number\r\nNone.\r\n\r\n## Checks\r\n\r\n- [] I've run `scripts/format.sh` to lint the changes in this PR.\r\nAlmost:\r\n```\r\nWARNING: Ray uses flake8 3.7.7, You currently are using 3.8.4. This might generate different results.\r\nWARNING: Ray uses yapf 0.23.0, You currently are using 0.30.0. This might generate different results.\r\nWARNING: Ray uses shellcheck 0.7.1, You currently are using 0.5.0. This might generate different results.\r\nWARNING: Ray uses mypy 0.782, You currently are using 0.790. This might generate different results.\r\nWARNING: Ray uses clang-format 7.0.0, You currently are using 9.0.0. This might generate different results.\r\nFrom https://github.com/ray-project/ray\r\n * branch                master     -> FETCH_HEAD\r\nTraceback (most recent call last):\r\n  File \"ci/travis/check_import_order.py\", line 68, in <module>\r\n    all_py_files = glob.glob(\"*.py\", recursive=True)\r\nTypeError: glob() got an unexpected keyword argument 'recursive'\r\n```\r\nAnyway, the `pylint --rcfile pylintrc` run was a 10/10\r\n\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n   - [x] Given that it requires the installation of SUMO simulator, I tested it in https://github.com/lcodeca/rllibsumodocker/tree/rllib-integration \r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/10266",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/10266/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/10266/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/10266/events",
        "html_url": "https://github.com/ray-project/ray/pull/10266",
        "id": 684105466,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDcyMDY2OTc5",
        "number": 10266,
        "title": "[core] fix the stacktrace",
        "user": {
            "login": "richardliaw",
            "id": 4529381,
            "node_id": "MDQ6VXNlcjQ1MjkzODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/richardliaw",
            "html_url": "https://github.com/richardliaw",
            "followers_url": "https://api.github.com/users/richardliaw/followers",
            "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
            "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
            "organizations_url": "https://api.github.com/users/richardliaw/orgs",
            "repos_url": "https://api.github.com/users/richardliaw/repos",
            "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/richardliaw/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-08-23T03:08:23Z",
        "updated_at": "2020-08-23T17:33:30Z",
        "closed_at": "2020-08-23T17:33:30Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/10266",
            "html_url": "https://github.com/ray-project/ray/pull/10266",
            "diff_url": "https://github.com/ray-project/ray/pull/10266.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/10266.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\n\n## Why are these changes needed?\nThis should now go from:\n\n```\nTraceback (most recent call last):\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/signature.py\", line 115, in flatten_args\n    reconstructed_signature.bind(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/inspect.py\", line 3015, in bind\n    return args[0]._bind(args[1:], kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/inspect.py\", line 3006, in _bind\n    arg=next(iter(kwargs))))\nTypeError: got an unexpected keyword argument 'world_size'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/ray_example.py\", line 149, in <module>\n    coordinator = Coordinator.remote(world_size=num_workers, verbose=2)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/actor.py\", line 379, in remote\n    return self._remote(args=args, kwargs=kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/actor.py\", line 568, in _remote\n    kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/signature.py\", line 117, in flatten_args\n    raise TypeError(str(exc))\nTypeError: got an unexpected keyword argument 'world_size'\n```\n\nto:\n\n```\nTraceback (most recent call last):\n  File \"/home/ubuntu/ray_example.py\", line 149, in <module>\n    coordinator = Coordinator.remote(world_size=num_workers, verbose=2)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/actor.py\", line 379, in remote\n    return self._remote(args=args, kwargs=kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/actor.py\", line 568, in _remote\n    kwargs)\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/signature.py\", line 117, in flatten_args\n    raise TypeError(str(exc)) from None\nTypeError: got an unexpected keyword argument 'world_size'\nError: Command failed:\n```\n<!-- Please give a short summary of the change and the problem this solves. -->\n\n## Related issue number\n\n<!-- For example: \"Closes #1234\" -->\n\n## Checks\n\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.\n- Testing Strategy\n   - [ ] Unit tests\n   - [ ] Release tests\n   - [ ] This PR is not tested (please justify below)",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/10966",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/10966/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/10966/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/10966/events",
        "html_url": "https://github.com/ray-project/ray/pull/10966",
        "id": 706882112,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDkxMzYzNjk0",
        "number": 10966,
        "title": "[Autoscaler] Fix k8s command runner when command fails",
        "user": {
            "login": "allenyin55",
            "id": 17361997,
            "node_id": "MDQ6VXNlcjE3MzYxOTk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/17361997?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/allenyin55",
            "html_url": "https://github.com/allenyin55",
            "followers_url": "https://api.github.com/users/allenyin55/followers",
            "following_url": "https://api.github.com/users/allenyin55/following{/other_user}",
            "gists_url": "https://api.github.com/users/allenyin55/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/allenyin55/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/allenyin55/subscriptions",
            "organizations_url": "https://api.github.com/users/allenyin55/orgs",
            "repos_url": "https://api.github.com/users/allenyin55/repos",
            "events_url": "https://api.github.com/users/allenyin55/events{/privacy}",
            "received_events_url": "https://api.github.com/users/allenyin55/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "wuisawesome",
            "id": 3980609,
            "node_id": "MDQ6VXNlcjM5ODA2MDk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3980609?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wuisawesome",
            "html_url": "https://github.com/wuisawesome",
            "followers_url": "https://api.github.com/users/wuisawesome/followers",
            "following_url": "https://api.github.com/users/wuisawesome/following{/other_user}",
            "gists_url": "https://api.github.com/users/wuisawesome/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wuisawesome/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wuisawesome/subscriptions",
            "organizations_url": "https://api.github.com/users/wuisawesome/orgs",
            "repos_url": "https://api.github.com/users/wuisawesome/repos",
            "events_url": "https://api.github.com/users/wuisawesome/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wuisawesome/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "wuisawesome",
                "id": 3980609,
                "node_id": "MDQ6VXNlcjM5ODA2MDk=",
                "avatar_url": "https://avatars.githubusercontent.com/u/3980609?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/wuisawesome",
                "html_url": "https://github.com/wuisawesome",
                "followers_url": "https://api.github.com/users/wuisawesome/followers",
                "following_url": "https://api.github.com/users/wuisawesome/following{/other_user}",
                "gists_url": "https://api.github.com/users/wuisawesome/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/wuisawesome/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wuisawesome/subscriptions",
                "organizations_url": "https://api.github.com/users/wuisawesome/orgs",
                "repos_url": "https://api.github.com/users/wuisawesome/repos",
                "events_url": "https://api.github.com/users/wuisawesome/events{/privacy}",
                "received_events_url": "https://api.github.com/users/wuisawesome/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "richardliaw",
                "id": 4529381,
                "node_id": "MDQ6VXNlcjQ1MjkzODE=",
                "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/richardliaw",
                "html_url": "https://github.com/richardliaw",
                "followers_url": "https://api.github.com/users/richardliaw/followers",
                "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
                "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
                "organizations_url": "https://api.github.com/users/richardliaw/orgs",
                "repos_url": "https://api.github.com/users/richardliaw/repos",
                "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
                "received_events_url": "https://api.github.com/users/richardliaw/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 5,
        "created_at": "2020-09-23T01:55:25Z",
        "updated_at": "2020-09-23T20:25:50Z",
        "closed_at": "2020-09-23T20:25:50Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/10966",
            "html_url": "https://github.com/ray-project/ray/pull/10966",
            "diff_url": "https://github.com/ray-project/ray/pull/10966.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/10966.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\nFix the exception that is raised when the command exits on failure (instead of exiting) when using the k8s command runner. \r\n\r\nFor example, when executing \r\n```bash\r\nray exec cluster.yaml 'command -v foo >/dev/null 2>&1'\r\n``` \r\nThe following exception is raised\r\n\r\n```\r\nTypeError: can only concatenate str (not \"list\") to str\r\n```\r\nLikely related to https://github.com/ray-project/ray/pull/10766.\r\n\r\nTested manually on minikube.\r\n\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\n\r\n## Related issue number\r\n\r\n<!-- For example: \"Closes #1234\" -->\r\n\r\n## Checks\r\n\r\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested :(\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/9952",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/9952/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/9952/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/9952/events",
        "html_url": "https://github.com/ray-project/ray/pull/9952",
        "id": 674279319,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDYzOTk4ODQ3",
        "number": 9952,
        "title": "fix iterable dataset (issue 9899)",
        "user": {
            "login": "yushan111",
            "id": 12656939,
            "node_id": "MDQ6VXNlcjEyNjU2OTM5",
            "avatar_url": "https://avatars.githubusercontent.com/u/12656939?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yushan111",
            "html_url": "https://github.com/yushan111",
            "followers_url": "https://api.github.com/users/yushan111/followers",
            "following_url": "https://api.github.com/users/yushan111/following{/other_user}",
            "gists_url": "https://api.github.com/users/yushan111/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yushan111/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yushan111/subscriptions",
            "organizations_url": "https://api.github.com/users/yushan111/orgs",
            "repos_url": "https://api.github.com/users/yushan111/repos",
            "events_url": "https://api.github.com/users/yushan111/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yushan111/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "richardliaw",
            "id": 4529381,
            "node_id": "MDQ6VXNlcjQ1MjkzODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/richardliaw",
            "html_url": "https://github.com/richardliaw",
            "followers_url": "https://api.github.com/users/richardliaw/followers",
            "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
            "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
            "organizations_url": "https://api.github.com/users/richardliaw/orgs",
            "repos_url": "https://api.github.com/users/richardliaw/repos",
            "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/richardliaw/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "richardliaw",
                "id": 4529381,
                "node_id": "MDQ6VXNlcjQ1MjkzODE=",
                "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/richardliaw",
                "html_url": "https://github.com/richardliaw",
                "followers_url": "https://api.github.com/users/richardliaw/followers",
                "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
                "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
                "organizations_url": "https://api.github.com/users/richardliaw/orgs",
                "repos_url": "https://api.github.com/users/richardliaw/repos",
                "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
                "received_events_url": "https://api.github.com/users/richardliaw/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 2,
        "created_at": "2020-08-06T12:35:20Z",
        "updated_at": "2020-08-23T02:40:39Z",
        "closed_at": "2020-08-23T02:40:39Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/9952",
            "html_url": "https://github.com/ray-project/ray/pull/9952",
            "diff_url": "https://github.com/ray-project/ray/pull/9952.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/9952.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n## Why are these changes needed?\r\n\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\nThis solve the TypeError caused by passing a validation_loader with an iterable dataset.\r\n\r\n## Related issue number\r\n\r\nissue #9899 \r\n<!-- For example: \"Closes #1234\" -->\r\n\r\n## Checks\r\n\r\n- [x] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [x] This PR is not tested (please justify below)\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/10514",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/10514/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/10514/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/10514/events",
        "html_url": "https://github.com/ray-project/ray/pull/10514",
        "id": 691474405,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDc4MjE2NDIy",
        "number": 10514,
        "title": "Fix passing system-config parameter to ray start",
        "user": {
            "login": "edoakes",
            "id": 9871461,
            "node_id": "MDQ6VXNlcjk4NzE0NjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9871461?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/edoakes",
            "html_url": "https://github.com/edoakes",
            "followers_url": "https://api.github.com/users/edoakes/followers",
            "following_url": "https://api.github.com/users/edoakes/following{/other_user}",
            "gists_url": "https://api.github.com/users/edoakes/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/edoakes/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/edoakes/subscriptions",
            "organizations_url": "https://api.github.com/users/edoakes/orgs",
            "repos_url": "https://api.github.com/users/edoakes/repos",
            "events_url": "https://api.github.com/users/edoakes/events{/privacy}",
            "received_events_url": "https://api.github.com/users/edoakes/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 2240357469,
                "node_id": "MDU6TGFiZWwyMjQwMzU3NDY5",
                "url": "https://api.github.com/repos/ray-project/ray/labels/@author-action-required",
                "name": "@author-action-required",
                "color": "ea91a3",
                "default": false,
                "description": "The PR author is responsible for the next step. Remove tag to send back to the reviewer."
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "stephanie-wang",
            "id": 2560516,
            "node_id": "MDQ6VXNlcjI1NjA1MTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2560516?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/stephanie-wang",
            "html_url": "https://github.com/stephanie-wang",
            "followers_url": "https://api.github.com/users/stephanie-wang/followers",
            "following_url": "https://api.github.com/users/stephanie-wang/following{/other_user}",
            "gists_url": "https://api.github.com/users/stephanie-wang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/stephanie-wang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/stephanie-wang/subscriptions",
            "organizations_url": "https://api.github.com/users/stephanie-wang/orgs",
            "repos_url": "https://api.github.com/users/stephanie-wang/repos",
            "events_url": "https://api.github.com/users/stephanie-wang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/stephanie-wang/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "stephanie-wang",
                "id": 2560516,
                "node_id": "MDQ6VXNlcjI1NjA1MTY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2560516?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stephanie-wang",
                "html_url": "https://github.com/stephanie-wang",
                "followers_url": "https://api.github.com/users/stephanie-wang/followers",
                "following_url": "https://api.github.com/users/stephanie-wang/following{/other_user}",
                "gists_url": "https://api.github.com/users/stephanie-wang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stephanie-wang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stephanie-wang/subscriptions",
                "organizations_url": "https://api.github.com/users/stephanie-wang/orgs",
                "repos_url": "https://api.github.com/users/stephanie-wang/repos",
                "events_url": "https://api.github.com/users/stephanie-wang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stephanie-wang/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-09-02T22:22:18Z",
        "updated_at": "2020-09-03T18:18:22Z",
        "closed_at": "2020-09-03T18:18:22Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/10514",
            "html_url": "https://github.com/ray-project/ray/pull/10514",
            "diff_url": "https://github.com/ray-project/ray/pull/10514.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/10514.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\nFixes a bug introduced in https://github.com/ray-project/ray/pull/10333 where passing a valid json dict to `--system-config` threw the following error because we `json.loads`'ed it twice:\r\n```\r\ncode/ray % ray start --head --system-config=\"{\\\"1\\\": \\\"2\\\"}\"                                                   \r\nTraceback (most recent call last):                                                                             \r\n  File \"/Users/eoakes/anaconda3/bin/ray\", line 11, in <module>                                                 \r\n    load_entry_point('ray', 'console_scripts', 'ray')()                                                        \r\n  File \"/Users/eoakes/code/ray/python/ray/scripts/scripts.py\", line 1599, in main                              \r\n    return cli()                                                                                               \r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py\", line 764, in __call__              \r\n    return self.main(*args, **kwargs)                                                                          \r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py\", line 717, in main                  \r\n    rv = self.invoke(ctx)                                                                                      \r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py\", line 1137, in invoke               \r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                    \r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py\", line 956, in invoke                \r\n    return ctx.invoke(self.callback, **ctx.params)                                                             \r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/site-packages/click/core.py\", line 555, in invoke                \r\n    return callback(*args, **kwargs)                                                                           \r\n  File \"/Users/eoakes/code/ray/python/ray/scripts/scripts.py\", line 510, in start\r\n    if system_config else system_config,\r\n  File \"/Users/eoakes/anaconda3/lib/python3.6/json/__init__.py\", line 348, in loads\r\n    'not {!r}'.format(s.__class__.__name__))\r\nTypeError: the JSON object must be str, bytes or bytearray, not 'dict'\r\n```\r\n\r\nAlso adds a test.\r\n\r\n## Related issue number\r\n\r\nCloses https://github.com/ray-project/ray/issues/10515\r\n\r\n## Checks\r\n\r\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested (please justify below)\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/10425",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/10425/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/10425/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/10425/events",
        "html_url": "https://github.com/ray-project/ray/pull/10425",
        "id": 688635556,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDc1ODUwMDIy",
        "number": 10425,
        "title": "[hotfix] update scripts.py invalid invocation",
        "user": {
            "login": "richardliaw",
            "id": 4529381,
            "node_id": "MDQ6VXNlcjQ1MjkzODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/richardliaw",
            "html_url": "https://github.com/richardliaw",
            "followers_url": "https://api.github.com/users/richardliaw/followers",
            "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
            "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
            "organizations_url": "https://api.github.com/users/richardliaw/orgs",
            "repos_url": "https://api.github.com/users/richardliaw/repos",
            "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/richardliaw/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-08-30T01:49:12Z",
        "updated_at": "2020-08-30T06:16:26Z",
        "closed_at": "2020-08-30T06:16:26Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/10425",
            "html_url": "https://github.com/ray-project/ray/pull/10425",
            "diff_url": "https://github.com/ray-project/ray/pull/10425.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/10425.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n<!-- Please add a reviewer to the assignee section when you create a PR. If you don't have the access to it, we will shortly find a reviewer and assign them to your PR. -->\r\n\r\n## Why are these changes needed?\r\n\r\n```\r\n==> /tmp/ray/session_2020-08-30_01-47-33_393277_81299/logs/monitor.out <==\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/anaconda3/bin/ray\", line 8, in <module>\r\n    sys.exit(main())\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py\", line 1600, in main\r\n    return cli()\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py\", line 782, in main\r\n    rv = self.invoke(ctx)\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py\", line 465, in start\r\n    address, redis_address)\r\nTypeError: validate_redis_address() takes 1 positional argument but 2 were given\r\n```\r\n<!-- Please give a short summary of the change and the problem this solves. -->\r\n\r\n## Related issue number\r\n\r\n<!-- For example: \"Closes #1234\" -->\r\n\r\n## Checks\r\n\r\n- [ ] I've run `scripts/format.sh` to lint the changes in this PR.\r\n- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.\r\n- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.\r\n- Testing Strategy\r\n   - [ ] Unit tests\r\n   - [ ] Release tests\r\n   - [ ] This PR is not tested (please justify below)",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/5530",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/5530/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/5530/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/5530/events",
        "html_url": "https://github.com/ray-project/ray/pull/5530",
        "id": 484855848,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzEwNjM2Mjgz",
        "number": 5530,
        "title": "Fixed: missing brackets when appending proc info on OutOfMemory",
        "user": {
            "login": "akharitonov",
            "id": 32765888,
            "node_id": "MDQ6VXNlcjMyNzY1ODg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/32765888?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/akharitonov",
            "html_url": "https://github.com/akharitonov",
            "followers_url": "https://api.github.com/users/akharitonov/followers",
            "following_url": "https://api.github.com/users/akharitonov/following{/other_user}",
            "gists_url": "https://api.github.com/users/akharitonov/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/akharitonov/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/akharitonov/subscriptions",
            "organizations_url": "https://api.github.com/users/akharitonov/orgs",
            "repos_url": "https://api.github.com/users/akharitonov/repos",
            "events_url": "https://api.github.com/users/akharitonov/events{/privacy}",
            "received_events_url": "https://api.github.com/users/akharitonov/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-08-24T19:44:50Z",
        "updated_at": "2019-08-25T01:33:21Z",
        "closed_at": "2019-08-25T01:33:21Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/5530",
            "html_url": "https://github.com/ray-project/ray/pull/5530",
            "diff_url": "https://github.com/ray-project/ray/pull/5530.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/5530.patch"
        },
        "body": "## Why are these changes needed?\r\n\r\nproc_stats.append was missing the set of brackets when adding a tuple to the list, which resulted in runtime error instead of correct Out of Memory message display.\r\n\r\n```\r\nFile \"/lib/python3.7/site-packages/ray/memory_monitor.py\", line 46, in get_message\r\n    proc_stats.append(get_rss(proc.memory_info()), pid, proc.cmdline())\r\nTypeError: append() takes exactly one argument (3 given)\r\n```\r\n\r\n## What do these changes do?\r\n\r\nBugfix\r\n\r\n## Related issue number\r\n\r\n-\r\n\r\n## Linter\r\n\r\n- [*] I've run `scripts/format.sh` to lint the changes in this PR.\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/5466",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/5466/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/5466/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/5466/events",
        "html_url": "https://github.com/ray-project/ray/pull/5466",
        "id": 481805294,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzA4MjM0NjAw",
        "number": 5466,
        "title": "Fix json.loads compatibility issue for Python 3.5",
        "user": {
            "login": "mitchellstern",
            "id": 3311523,
            "node_id": "MDQ6VXNlcjMzMTE1MjM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3311523?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mitchellstern",
            "html_url": "https://github.com/mitchellstern",
            "followers_url": "https://api.github.com/users/mitchellstern/followers",
            "following_url": "https://api.github.com/users/mitchellstern/following{/other_user}",
            "gists_url": "https://api.github.com/users/mitchellstern/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mitchellstern/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mitchellstern/subscriptions",
            "organizations_url": "https://api.github.com/users/mitchellstern/orgs",
            "repos_url": "https://api.github.com/users/mitchellstern/repos",
            "events_url": "https://api.github.com/users/mitchellstern/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mitchellstern/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-08-16T22:17:07Z",
        "updated_at": "2019-08-17T08:27:45Z",
        "closed_at": "2019-08-17T07:33:56Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/5466",
            "html_url": "https://github.com/ray-project/ray/pull/5466",
            "diff_url": "https://github.com/ray-project/ray/pull/5466.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/5466.patch"
        },
        "body": "<!-- Thank you for your contribution! Please review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request. -->\r\n\r\n## Why are these changes needed?\r\n\r\nBefore Python 3.6, the `json.loads` function could only accept `str` objects, not `bytes` objects. See the documentation at https://docs.python.org/3/library/json.html#json.loads for details.\r\n\r\n## What do these changes do?\r\n\r\nDecode the `bytes` messages coming from the Redis client into `str` objects in order to avoid the following type error in Python versions 3.0 to 3.5:\r\n\r\n```\r\nTypeError: the JSON object must be str, not 'bytes'\r\n```\r\n\r\n## Related issue number\r\n\r\nN/A\r\n\r\n## Linter\r\n\r\n- [x] I've run `scripts/format.sh` to lint the changes in this PR.\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/4221",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/4221/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/4221/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/4221/events",
        "html_url": "https://github.com/ray-project/ray/pull/4221",
        "id": 416383886,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjU3NjU2OTYy",
        "number": 4221,
        "title": "Add type check in free and change Exception to TypeError",
        "user": {
            "login": "guoyuhong",
            "id": 19584326,
            "node_id": "MDQ6VXNlcjE5NTg0MzI2",
            "avatar_url": "https://avatars.githubusercontent.com/u/19584326?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/guoyuhong",
            "html_url": "https://github.com/guoyuhong",
            "followers_url": "https://api.github.com/users/guoyuhong/followers",
            "following_url": "https://api.github.com/users/guoyuhong/following{/other_user}",
            "gists_url": "https://api.github.com/users/guoyuhong/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/guoyuhong/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/guoyuhong/subscriptions",
            "organizations_url": "https://api.github.com/users/guoyuhong/orgs",
            "repos_url": "https://api.github.com/users/guoyuhong/repos",
            "events_url": "https://api.github.com/users/guoyuhong/events{/privacy}",
            "received_events_url": "https://api.github.com/users/guoyuhong/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2019-03-02T10:35:06Z",
        "updated_at": "2019-03-04T08:40:09Z",
        "closed_at": "2019-03-04T08:40:05Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/4221",
            "html_url": "https://github.com/ray-project/ray/pull/4221",
            "diff_url": "https://github.com/ray-project/ray/pull/4221.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/4221.patch"
        },
        "body": "<!--\r\nThank you for your contribution!\r\n\r\nPlease review https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before opening a pull request.\r\n-->\r\n\r\n## What do these changes do?\r\nWe found strange worker error without call stack.\r\n```\r\nTypeError: Cannot convert ray._raylet.TaskID to ray._raylet.ObjectID\r\nException ignored in: 'ray._raylet.ObjectIDsToVector'\r\n```\r\nFinally, it is found that there is no type check in `ray.internal.free`. We add the similar type check like `ray.get` and `ray.wait`.\r\n<!-- Please give a short brief about these changes. -->\r\n\r\n## Related issue number\r\nN/A\r\n<!-- Are there any issues opened that will be resolved by merging this change? -->\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/2889",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/2889/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/2889/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/2889/events",
        "html_url": "https://github.com/ray-project/ray/pull/2889",
        "id": 360522897,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjE1NzU5NDk4",
        "number": 2889,
        "title": "[tune] Tweaks to Trainable and Verbosity",
        "user": {
            "login": "richardliaw",
            "id": 4529381,
            "node_id": "MDQ6VXNlcjQ1MjkzODE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4529381?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/richardliaw",
            "html_url": "https://github.com/richardliaw",
            "followers_url": "https://api.github.com/users/richardliaw/followers",
            "following_url": "https://api.github.com/users/richardliaw/following{/other_user}",
            "gists_url": "https://api.github.com/users/richardliaw/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/richardliaw/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/richardliaw/subscriptions",
            "organizations_url": "https://api.github.com/users/richardliaw/orgs",
            "repos_url": "https://api.github.com/users/richardliaw/repos",
            "events_url": "https://api.github.com/users/richardliaw/events{/privacy}",
            "received_events_url": "https://api.github.com/users/richardliaw/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "ericl",
            "id": 14922,
            "node_id": "MDQ6VXNlcjE0OTIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/14922?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ericl",
            "html_url": "https://github.com/ericl",
            "followers_url": "https://api.github.com/users/ericl/followers",
            "following_url": "https://api.github.com/users/ericl/following{/other_user}",
            "gists_url": "https://api.github.com/users/ericl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ericl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ericl/subscriptions",
            "organizations_url": "https://api.github.com/users/ericl/orgs",
            "repos_url": "https://api.github.com/users/ericl/repos",
            "events_url": "https://api.github.com/users/ericl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ericl/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "ericl",
                "id": 14922,
                "node_id": "MDQ6VXNlcjE0OTIy",
                "avatar_url": "https://avatars.githubusercontent.com/u/14922?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ericl",
                "html_url": "https://github.com/ericl",
                "followers_url": "https://api.github.com/users/ericl/followers",
                "following_url": "https://api.github.com/users/ericl/following{/other_user}",
                "gists_url": "https://api.github.com/users/ericl/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ericl/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ericl/subscriptions",
                "organizations_url": "https://api.github.com/users/ericl/orgs",
                "repos_url": "https://api.github.com/users/ericl/repos",
                "events_url": "https://api.github.com/users/ericl/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ericl/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 24,
        "created_at": "2018-09-15T09:09:46Z",
        "updated_at": "2018-10-12T06:42:22Z",
        "closed_at": "2018-10-12T06:42:14Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/2889",
            "html_url": "https://github.com/ray-project/ray/pull/2889",
            "diff_url": "https://github.com/ray-project/ray/pull/2889.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/2889.patch"
        },
        "body": "Fix HyperOpt verbosity (hopefully), and tweak Trainable.\r\n\r\n\r\nTODOs:\r\n\r\n - [x] when I had a dict of state, I still had to write file saving/restoring code\r\n - [x] the semantics of checkpoint_dir vs checkpoint_path was unclear, perhaps it could use an example in the interface class\r\n - [x] it wasn't super clear that self.config was automatically set, perhaps it should be an argument for _setup()\r\n - [x] the error message for when you return None / the wrong thing from _train() is hard to understand\r\n\r\nFrom Ray-dev discussion: We should increase the clarity on the docs.\r\nhttps://groups.google.com/forum/#!topic/ray-dev/wx5zdzbgMfs\r\n\r\n\r\n- [x] \"Suggestion Algorithms like HyperOpt don't extend the VariantGenerator so `lambda spec: ...`\"\r\n\r\n- [x] Clean up HyperOptSearch (don't expose `add_configurations`)\r\n\r\n- [x] Clean up HyperBand documentation\r\n\r\n- [x] Provide a better error when a config is mis-specified.\r\n\r\n```\r\n  File \"<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/trial_runner.py\", line 199, in has_resources\r\n    return self.trial_executor.has_resources(resources)\r\n  File \"<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/ray_trial_executor.py\", line 206, in has_resources\r\n    have_space = (resources.cpu_total() <= cpu_avail\r\n  File \"<PROJECT_HOME>/env_27/lib/python2.7/site-packages/ray/tune/trial.py\", line 55, in cpu_total\r\n    return self.cpu + self.extra_cpu\r\nTypeError: unsupported operand type(s) for +: 'function' and 'int'\r\n```\r\n\r\n#2870 #2888.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/1535",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/1535/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/1535/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/1535/events",
        "html_url": "https://github.com/ray-project/ray/pull/1535",
        "id": 296645467,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTY4Nzc3MDE3",
        "number": 1535,
        "title": "Minor, change NotImplemented -> NotImplementedError.",
        "user": {
            "login": "robertnishihara",
            "id": 249517,
            "node_id": "MDQ6VXNlcjI0OTUxNw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/249517?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/robertnishihara",
            "html_url": "https://github.com/robertnishihara",
            "followers_url": "https://api.github.com/users/robertnishihara/followers",
            "following_url": "https://api.github.com/users/robertnishihara/following{/other_user}",
            "gists_url": "https://api.github.com/users/robertnishihara/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/robertnishihara/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/robertnishihara/subscriptions",
            "organizations_url": "https://api.github.com/users/robertnishihara/orgs",
            "repos_url": "https://api.github.com/users/robertnishihara/repos",
            "events_url": "https://api.github.com/users/robertnishihara/events{/privacy}",
            "received_events_url": "https://api.github.com/users/robertnishihara/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2018-02-13T08:05:43Z",
        "updated_at": "2018-02-17T01:08:34Z",
        "closed_at": "2018-02-17T01:08:26Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/1535",
            "html_url": "https://github.com/ray-project/ray/pull/1535",
            "diff_url": "https://github.com/ray-project/ray/pull/1535.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/1535.patch"
        },
        "body": "I'm seeing tons of error messages in Jenkins like the following. For some reason they are not failing the Jenkins build..\r\n\r\n```\r\n('=== Testing', 'A3C', [Box(5,), Box(5,)], Tuple(Discrete(10), Box(5,)), '===')\r\nObservation shape is ((10,), (5,))\r\nUsing a TupleFlatteningPreprocessor\r\nCreating sub-preprocessor for Discrete(10)\r\nObservation shape is (10,)\r\nUsing one-hot preprocessor for discrete envs.\r\nCreating sub-preprocessor for Box(5,)\r\nObservation shape is (5,)\r\nNot using any observation preprocessor.\r\nSetting up loss\r\n'NotImplementedType' object is not callable\r\nTraceback (most recent call last):\r\n  File \"/ray/python/ray/rllib/test/test_supported_spaces.py\", line 84, in check_support\r\n    a = get_agent_class(alg)(config=config, env=\"stub_env\")\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/agent.py\", line 84, in __init__\r\n    Trainable.__init__(self, config, registry, logger_creator)\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/tune/trainable.py\", line 88, in __init__\r\n    self._setup()\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/agent.py\", line 107, in _setup\r\n    self._init()\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/a3c/a3c.py\", line 74, in _init\r\n    start_sampler=False)\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/a3c/a3c_evaluator.py\", line 37, in __init__\r\n    registry, env.observation_space.shape, env.action_space, config)\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/a3c/shared_model.py\", line 18, in __init__\r\n    registry, ob_space, ac_space, config, **kwargs)\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/a3c/tfpolicy.py\", line 27, in __init__\r\n    self.setup_loss(action_space)\r\n  File \"/opt/conda/lib/python2.7/site-packages/ray-0.3.1-py2.7-linux-x86_64.egg/ray/rllib/a3c/tfpolicy.py\", line 43, in setup_loss\r\n    \"currently not supported\")\r\nTypeError: 'NotImplementedType' object is not callable\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/991",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/991/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/991/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/991/events",
        "html_url": "https://github.com/ray-project/ray/pull/991",
        "id": 258284845,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTQxNDc1NzI0",
        "number": 991,
        "title": "Pass string into json.loads, not bytes object.",
        "user": {
            "login": "robertnishihara",
            "id": 249517,
            "node_id": "MDQ6VXNlcjI0OTUxNw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/249517?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/robertnishihara",
            "html_url": "https://github.com/robertnishihara",
            "followers_url": "https://api.github.com/users/robertnishihara/followers",
            "following_url": "https://api.github.com/users/robertnishihara/following{/other_user}",
            "gists_url": "https://api.github.com/users/robertnishihara/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/robertnishihara/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/robertnishihara/subscriptions",
            "organizations_url": "https://api.github.com/users/robertnishihara/orgs",
            "repos_url": "https://api.github.com/users/robertnishihara/repos",
            "events_url": "https://api.github.com/users/robertnishihara/events{/privacy}",
            "received_events_url": "https://api.github.com/users/robertnishihara/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 4,
        "created_at": "2017-09-17T07:09:55Z",
        "updated_at": "2017-10-04T20:58:27Z",
        "closed_at": "2017-10-01T21:56:40Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/991",
            "html_url": "https://github.com/ray-project/ray/pull/991",
            "diff_url": "https://github.com/ray-project/ray/pull/991.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/991.patch"
        },
        "body": "This should fix an error I was seeing with Python 3.5 in `monitor.py`.\r\n\r\n```\r\nINFO:root:Driver cada6249d73320004f3f128bbb5d00722e9e1685 has been removed.\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/ray/python/ray/monitor.py\", line 479, in <module>\r\n    monitor.run()\r\n  File \"/home/ubuntu/ray/python/ray/monitor.py\", line 430, in run\r\n    self.process_messages()\r\n  File \"/home/ubuntu/ray/python/ray/monitor.py\", line 390, in process_messages\r\n    message_handler(channel, data)\r\n  File \"/home/ubuntu/ray/python/ray/monitor.py\", line 325, in driver_removed_handler\r\n    else json.loads(result))\r\n  File \"/home/ubuntu/anaconda3/lib/python3.5/json/__init__.py\", line 312, in loads\r\n    s.__class__.__name__))\r\nTypeError: the JSON object must be str, not 'bytes'\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/ray-project/ray/issues/253",
        "repository_url": "https://api.github.com/repos/ray-project/ray",
        "labels_url": "https://api.github.com/repos/ray-project/ray/issues/253/labels{/name}",
        "comments_url": "https://api.github.com/repos/ray-project/ray/issues/253/comments",
        "events_url": "https://api.github.com/repos/ray-project/ray/issues/253/events",
        "html_url": "https://github.com/ray-project/ray/pull/253",
        "id": 205854519,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTA0OTgxODAy",
        "number": 253,
        "title": "fix segfault in photon.Task",
        "user": {
            "login": "pcmoritz",
            "id": 113316,
            "node_id": "MDQ6VXNlcjExMzMxNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/113316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pcmoritz",
            "html_url": "https://github.com/pcmoritz",
            "followers_url": "https://api.github.com/users/pcmoritz/followers",
            "following_url": "https://api.github.com/users/pcmoritz/following{/other_user}",
            "gists_url": "https://api.github.com/users/pcmoritz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pcmoritz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pcmoritz/subscriptions",
            "organizations_url": "https://api.github.com/users/pcmoritz/orgs",
            "repos_url": "https://api.github.com/users/pcmoritz/repos",
            "events_url": "https://api.github.com/users/pcmoritz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pcmoritz/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2017-02-07T11:04:08Z",
        "updated_at": "2017-02-07T19:17:12Z",
        "closed_at": "2017-02-07T19:17:12Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/ray-project/ray/pulls/253",
            "html_url": "https://github.com/ray-project/ray/pull/253",
            "diff_url": "https://github.com/ray-project/ray/pull/253.diff",
            "patch_url": "https://github.com/ray-project/ray/pull/253.patch"
        },
        "body": "Before:\r\n```\r\nIn [1]: import photon\r\n\r\nIn [2]: photon.Task()\r\nSegmentation fault (core dumped)\r\n```\r\n\r\nAfter:\r\n```\r\nIn [1]: import photon\r\n\r\nIn [2]: photon.Task()\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-2-f8e88d989d6f> in <module>()\r\n----> 1 photon.Task()\r\n\r\nTypeError: function takes exactly 6 arguments (0 given)\r\n```\r\n\r\nThe problem was that the first if in PyTask_init returned, which means that `task->spec` is 0. This led to the constructor segfaulting.",
        "performed_via_github_app": null,
        "score": 1.0
    }
]